import { SeedResource } from './seedCategories.ts';

export const ADDITIONAL_RESOURCES: SeedResource[] = [
  // Additional Username tools
  {
    name: "Namecheckr",
    categorySlug: "username",
    url: "https://www.namecheckr.com",
    description: "Check brand and handle availability across domain names, trademark registries, and leading social channels.",
    usageContext: "Rapidly identify which platforms a target has not yet secured.",
    inputOutput: "Input: Handle | Output: Availability status grid",
    opsecNotes: "Queries are sent from server-side; safe passive lookup.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 110,
    views: 6500,
    tags: ["username", "branding", "availability"]
  },
  {
    name: "Keybase Identity Directory",
    categorySlug: "username",
    url: "https://keybase.io",
    description: "Cryptographically verifiable directory linking PGP public keys to Twitter, GitHub, Reddit, and website domains.",
    usageContext: "Proving cryptographic attribution: linking an anonymous handle to public keys and cross-signed identities.",
    inputOutput: "Input: Username or PGP key ID | Output: Verified linked proofs, public PGP key, follower tree",
    opsecNotes: "Proofs are cryptographically signed and publicly immutable on the Stellar blockchain.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 280,
    views: 18200,
    tags: ["username", "cryptography", "pgp", "identity-proofs"]
  },
  {
    name: "GitHub User Search API",
    categorySlug: "username",
    url: "https://github.com/search?type=users",
    description: "Search developer profiles, public commit histories, SSH keys, GPG keys, and email addresses in git commit logs.",
    usageContext: "Extracting personal email addresses leaked inside commit history headers (`git log`).",
    inputOutput: "Input: Username | Output: Repositories, commit history, SSH public keys (/username.keys)",
    opsecNotes: "Append '.keys' to any GitHub profile URL (e.g. github.com/torvalds.keys) to grab their public SSH keys instantly.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 470,
    views: 31000,
    tags: ["username", "github", "commit-history", "ssh-keys", "git"]
  },
  {
    name: "Gravatar Profile Lookup",
    categorySlug: "username",
    url: "https://en.gravatar.com",
    description: "Globally Recognized Avatar service linking hashed email addresses to public bios, websites, and photo avatars.",
    usageContext: "Querying `gravatar.com/avatar/{md5(email)}` or username to uncover associated WordPress accounts and profile images.",
    inputOutput: "Input: Email MD5 hash or username | Output: Public avatar photo, display name, linked websites",
    opsecNotes: "Email is hashed with standard MD5; can be reversed using rainbow tables.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 195,
    views: 12000,
    tags: ["username", "gravatar", "md5", "avatars"]
  },

  // Additional Email tools
  {
    name: "Snusbase",
    categorySlug: "email",
    url: "https://snusbase.com",
    description: "Database breach indexing service designed for security researchers and penetration testers to discover compromised data.",
    usageContext: "Locating historical passwords, IP logs, and linked usernames across legacy database breaches.",
    inputOutput: "Input: Email, username, IP, or phone | Output: Breach records, leaked passwords/hashes, source databases",
    opsecNotes: "Commercial subscription required; verify legality in your jurisdiction before querying personal data.",
    toolFlags: "R",
    isFree: 0,
    ratingAvg: 4.7,
    ratingCount: 320,
    views: 21500,
    tags: ["email", "breach", "snusbase", "password-hashes"]
  },
  {
    name: "LeakCheck.net",
    categorySlug: "email",
    url: "https://leakcheck.net",
    description: "Data breach search engine with over 7.5 billion entries to check if accounts have been compromised.",
    usageContext: "Checking if credentials have been exposed in recent or historical corporate compromises.",
    inputOutput: "Input: Email or username | Output: Compromised status, breach sources, partial credential preview",
    opsecNotes: "Offers free lookup tier with masked passwords.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.6,
    ratingCount: 230,
    views: 15400,
    tags: ["email", "breach", "leakcheck", "credentials"]
  },
  {
    name: "EmailFormat.com",
    categorySlug: "email",
    url: "https://www.email-format.com",
    description: "Discovers standard email address formats used by thousands of companies and educational institutions.",
    usageContext: "Determining whether an organization uses first.last@, flast@, or first@ patterns.",
    inputOutput: "Input: Company domain | Output: Syntactic email structure percentage breakdown",
    opsecNotes: "Passive directory check.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 140,
    views: 8900,
    tags: ["email", "corporate-syntax", "naming-conventions"]
  },
  {
    name: "Voila Norbert",
    categorySlug: "email",
    url: "https://www.voilanorbert.com",
    description: "Email finder with high deliverability verification and corporate contact enrichment.",
    usageContext: "Locating corporate executive direct email addresses for investigations.",
    inputOutput: "Input: Full name + Company domain | Output: Verified work email, confidence score",
    opsecNotes: "Provides 50 free leads upon sign-up.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.5,
    ratingCount: 160,
    views: 10400,
    tags: ["email", "corporate-leads", "enrichment"]
  },

  // Additional Domain tools
  {
    name: "Sublist3r",
    categorySlug: "domain",
    url: "https://github.com/aboul3la/Sublist3r",
    description: "Fast Python tool designed to enumerate subdomains of websites using search engines (Google, Yahoo, Bing, Baidu, Ask).",
    usageContext: "Passive subdomain harvesting across major worldwide search engines without hitting target servers directly.",
    inputOutput: "Input: Target domain | Output: List of discovered subdomains in plain text",
    opsecNotes: "Scrapes public search engine results; completely passive reconnaissance.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 390,
    views: 24900,
    tags: ["domain", "subdomains", "cli", "python", "passive"]
  },
  {
    name: "Assetfinder by tomnomnom",
    categorySlug: "domain",
    url: "https://github.com/tomnomnom/assetfinder",
    description: "Ultra-fast Go utility that finds domains and subdomains related to a given domain from multiple public sources.",
    usageContext: "Pipelining subdomain enumeration in automated bash/Go security recon scripts.",
    inputOutput: "Input: Domain string | Output: Standard out list of related assets and subdomains",
    opsecNotes: "Queries public archives and certificate logs.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 410,
    views: 26800,
    tags: ["domain", "recon", "golang", "cli", "fast"]
  },
  {
    name: "Waybackurls by tomnomnom",
    categorySlug: "domain",
    url: "https://github.com/tomnomnom/waybackurls",
    description: "Fetches all URLs that the Wayback Machine, Common Crawl, and VirusTotal have ever seen for a domain.",
    usageContext: "Discovering forgotten API endpoints, old PHP scripts, parameters, and secret admin paths indexed years ago.",
    inputOutput: "Input: Domain name | Output: Thousands of historic URLs, API endpoints, parameter lists",
    opsecNotes: "Priceless for finding vulnerable endpoints that developers forgot were ever online.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 29500,
    tags: ["domain", "endpoints", "historical-urls", "api-discovery"]
  },
  {
    name: "Shodan Favicon Hash Calculator",
    categorySlug: "domain",
    url: "https://github.com/m4ll0k/Shodan-Favicon-Hash",
    description: "Calculates the MurmurHash3 value of a website's favicon.ico to find all other servers on the internet using the same icon.",
    usageContext: "Pivoting on a unique favicon hash in Shodan (http.favicon.hash:XXXX) to locate origin IPs bypassing Cloudflare.",
    inputOutput: "Input: Favicon URL or icon file | Output: MurmurHash3 integer, ready-to-run Shodan dork",
    opsecNotes: "One of the most reliable methods to unmask hidden backends and command-and-control servers.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 19800,
    tags: ["domain", "favicon-hash", "shodan-dork", "origin-unmasking"]
  },

  // Additional IP tools
  {
    name: "BGPView",
    categorySlug: "ip-address",
    url: "https://bgpview.io",
    description: "Free and accessible API and web interface for looking up BGP routing, Autonomous System information, and prefixes.",
    usageContext: "Investigating ISP route announcements, upstream downstreams, and IP allocation blocks.",
    inputOutput: "Input: ASN or IP | Output: Visual routing tree, prefix counts, peers list",
    opsecNotes: "Clean, modern interface for network routing intelligence.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 290,
    views: 17600,
    tags: ["ip-address", "bgp", "asn", "peering", "routing"]
  },
  {
    name: "IPVoid Toolbox",
    categorySlug: "ip-address",
    url: "https://www.ipvoid.com",
    description: "Collection of IP tools: Blacklist Check, IP to Country, Ping, Traceroute, Whois, and HTTP Header inspector.",
    usageContext: "Checking an IP against 30+ DNSBL anti-spam and threat reputation blacklists simultaneously.",
    inputOutput: "Input: IP address | Output: Multi-engine blacklist scan report, reverse DNS, ISP info",
    opsecNotes: "Aggregates popular blacklist queries in one dashboard.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 220,
    views: 14200,
    tags: ["ip-address", "blacklists", "spam-check", "toolbox"]
  },
  {
    name: "ARIN Whois Directory",
    categorySlug: "ip-address",
    url: "https://whois.arin.net",
    description: "Official registry for North American IP addresses and ASNs, providing authoritative organizational allocations and POCs.",
    usageContext: "Finding the legal corporate owner, network abuse contacts, and point-of-contact phone numbers for an IP block.",
    inputOutput: "Input: IP address or NetRange | Output: Legal organization name, address, network admin contacts",
    opsecNotes: "Authoritative RIR registry; records are legally certified.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 260,
    views: 16800,
    tags: ["ip-address", "arin", "rir", "allocation", "abuse-poc"]
  },

  // Additional Social Media tools
  {
    name: "Osintgram",
    categorySlug: "social-media",
    url: "https://github.com/Datalux/Osintgram",
    description: "Instagram OSINT tool providing a shell interface to analyze followers, tagged photos, comments, and likers of a target profile.",
    usageContext: "Extracting common followers, tagged coordinates, and frequent commenters on a target Instagram account.",
    inputOutput: "Input: Target @handle | Output: Follower statistics, extracted emails, tagged locations, comment sentiment",
    opsecNotes: "Requires a dummy ('sock puppet') Instagram account to execute queries. NEVER use your personal account.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 350,
    views: 22500,
    tags: ["social-media", "instagram", "sock-puppet", "cli", "followers"]
  },
  {
    name: "Instaloader",
    categorySlug: "social-media",
    url: "https://github.com/instaloader/instaloader",
    description: "Download pictures (or videos) along with their captions and other metadata from Instagram posts, stories, and highlights.",
    usageContext: "Preserving a target's Instagram posts and captions locally in high resolution before they delete their account.",
    inputOutput: "Input: Profile or post URL | Output: Media files, JSON metadata, captions, timestamp records",
    opsecNotes: "Respect Instagram rate limits to avoid burner account bans.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 380,
    views: 24100,
    tags: ["social-media", "instagram", "downloader", "archival", "captions"]
  },
  {
    name: "Social Blade",
    categorySlug: "social-media",
    url: "https://socialblade.com",
    description: "Tracks user statistics for YouTube, Twitch, Instagram, Twitter, and TikTok, showing historical follower growth and subscriber spikes.",
    usageContext: "Detecting fake follower purchases (unnatural sudden vertical spikes) and assessing creator revenue estimates.",
    inputOutput: "Input: Channel or account handle | Output: Historical charts of subscriber growth, view counts, grades",
    opsecNotes: "Publicly visible third-party tracking; safe passive query.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 420,
    views: 27900,
    tags: ["social-media", "growth-charts", "fake-followers", "youtube", "tiktok"]
  },

  // Additional Geolocation tools
  {
    name: "NASA FIRMS Fire Information for Resource Management",
    categorySlug: "geolocation",
    url: "https://firms.modaps.eosdis.nasa.gov",
    description: "Near real-time active fire data from MODIS and VIIRS satellite instruments covering the globe.",
    usageContext: "Detecting artillery barrages, airstrikes, industrial explosions, and wildfires with thermal satellite heat signatures.",
    inputOutput: "Input: Global map coordinates + date | Output: Thermal anomaly pins with brightness temperature and confidence",
    opsecNotes: "Frequently used by conflict analysts to detect bombardment zones hours before news reports emerge.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 470,
    views: 30100,
    tags: ["geolocation", "nasa", "thermal-satellites", "fires", "conflict-zones"]
  },
  {
    name: "Mapillary Street-level Imagery",
    categorySlug: "geolocation",
    url: "https://www.mapillary.com",
    description: "Crowdsourced street-level photography platform featuring millions of geotagged photos from routes not covered by Google Street View.",
    usageContext: "Exploring remote roads, developing countries, hiking trails, and rural areas where official street view cars never drove.",
    inputOutput: "Input: Map coordinate / street | Output: Sequential high-res photos captured by dashcams and smartphones",
    opsecNotes: "Open alternative with exceptional rural and global coverage.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 19800,
    tags: ["geolocation", "crowdsourced", "street-imagery", "dashcams", "rural"]
  },
  {
    name: "ShadowCalculator",
    categorySlug: "geolocation",
    url: "http://shadowcalculator.eu",
    description: "Calculates sunlight and building shadow projections on Google Maps anywhere in the world for any given time of day.",
    usageContext: "Verifying the time of day a photo was taken by matching shadow lengths cast by known buildings and monuments.",
    inputOutput: "Input: Building position + height + date | Output: Projected shadow polygon overlaid on satellite imagery",
    opsecNotes: "Ideal pairing with SunCalc for forensic chronolocation.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 180,
    views: 11400,
    tags: ["geolocation", "chronolocation", "shadow-calculator", "building-shadows"]
  },
  {
    name: "USGS EarthExplorer",
    categorySlug: "geolocation",
    url: "https://earthexplorer.usgs.gov",
    description: "Official United States Geological Survey portal for downloading aerial photos, satellite data, elevation models, and land cover.",
    usageContext: "Obtaining historical declassified military spy satellite imagery (CORONA mission, 1960s-1970s) and high-res DEM elevation maps.",
    inputOutput: "Input: Geographic bounding box | Output: Downloadable raw GeoTIFF imagery files from USGS archives",
    opsecNotes: "Free account required for downloads; massive historical archive.",
    toolFlags: "R",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 340,
    views: 21800,
    tags: ["geolocation", "usgs", "elevation-maps", "corona-satellite", "geotiff"]
  },

  // Additional Search Dorks tools
  {
    name: "DorkSearch.com",
    categorySlug: "search-dorks",
    url: "https://dorksearch.com",
    description: "Fast Google Dork search engine and generator with thousands of pre-configured dorks categorized for bug bounty and OSINT.",
    usageContext: "Quickly launching complex dorks against target domains with one-click buttons.",
    inputOutput: "Input: Domain name + category | Output: Executable Google search URLs tailored to target",
    opsecNotes: "Automates query syntax construction without memorizing operators.",
    toolFlags: "D",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 320,
    views: 20400,
    tags: ["search-dorks", "dork-generator", "one-click", "bug-bounty"]
  },
  {
    name: "GitHub Dorks Repository by techgaun",
    categorySlug: "search-dorks",
    url: "https://github.com/techgaun/github-dorks",
    description: "Collection of GitHub search queries to locate sensitive files, API secrets, private RSA keys, and database passwords.",
    usageContext: "Scanning GitHub for leaked corporate credentials, AWS keys, and internal VPN configurations.",
    inputOutput: "Input: Target organization name | Output: Tailored GitHub search queries for secrets",
    opsecNotes: "Developers frequently commit private keys accidentally; these dorks pinpoint them.",
    toolFlags: "D",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 450,
    views: 29000,
    tags: ["search-dorks", "github-dorks", "api-keys", "credentials", "secrets"]
  },
  {
    name: "SearchCode",
    categorySlug: "search-dorks",
    url: "https://searchcode.com",
    description: "Comprehensive source code and documentation search engine indexing over 75 billion lines of code from 10+ open-source hosting sites.",
    usageContext: "Finding code examples, vulnerable functions, private API endpoint routes, and developer comments.",
    inputOutput: "Input: Function name, variable, or error string | Output: Matching open-source code repositories",
    opsecNotes: "Indexes Bitbucket, GitLab, Google Code, and GitHub simultaneously.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 240,
    views: 15900,
    tags: ["search-dorks", "source-code", "multi-repo", "code-search"]
  },

  // Additional Public Records tools
  {
    name: "Aleph by OCCRP",
    categorySlug: "public-records",
    url: "https://aleph.occrp.org",
    description: "Investigative data platform developed by the Organized Crime and Corruption Reporting Project indexing leaks, court records, and company filings.",
    usageContext: "Cross-referencing entities across international corruption investigations, gazettes, sanctions lists, and confidential leaks.",
    inputOutput: "Input: Person or corporate entity | Output: Documents, government gazettes, sanctions matches, relationship graphs",
    opsecNotes: "Premier investigative tool built by award-winning journalists.",
    toolFlags: "R",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 560,
    views: 37200,
    tags: ["public-records", "occrp", "corruption", "investigative-journalism", "gold-standard"]
  },
  {
    name: "OpenSecrets Lobbying & Political Finance",
    categorySlug: "public-records",
    url: "https://www.opensecrets.org",
    description: "Non-profit research group tracking money in U.S. politics and its effect on elections and public policy.",
    usageContext: "Investigating corporate political campaign donations, PAC contributions, foreign lobbying registrations, and lawmaker assets.",
    inputOutput: "Input: Politician, donor, or corporation | Output: Campaign donor breakdowns, PAC expenditures, registered lobbyists",
    opsecNotes: "Authoritative transparency record on American political expenditures.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 480,
    views: 31000,
    tags: ["public-records", "opensecrets", "campaign-finance", "lobbying", "pac"]
  },
  {
    name: "Sayari Graph",
    categorySlug: "public-records",
    url: "https://sayari.com",
    description: "Commercial risk intelligence platform connecting beneficial ownership data across frontier and hard-to-navigate jurisdictions.",
    usageContext: "Unmasking ultimate beneficial owners (UBO) hiding behind Russian, Chinese, Venezuelan, and Middle Eastern corporate shell structures.",
    inputOutput: "Input: Corporate entity or individual | Output: Multi-tiered beneficial ownership graph, corporate registry extracts",
    opsecNotes: "Industry leader in sanctioned jurisdiction asset tracing; enterprise subscription.",
    toolFlags: "R",
    isFree: 0,
    ratingAvg: 4.8,
    ratingCount: 230,
    views: 15600,
    tags: ["public-records", "beneficial-ownership", "ubo", "sanctions", "sayari"]
  },

  // Additional Document tools
  {
    name: "Oletools by Decalage",
    categorySlug: "documents-metadata",
    url: "https://github.com/decalage2/oletools",
    description: "Python tools to analyze Microsoft OLE2 and Office OpenXML files, extracting VBA macros, hidden streams, and malicious payloads.",
    usageContext: "Triage malicious Word/Excel attachments, deobfuscating auto-executing macros and malicious powershell downloaders.",
    inputOutput: "Input: .doc / .xls / .docx file | Output: VBA macro code, suspicious keywords (Shell, WScript), auto-open triggers",
    opsecNotes: "Standard utility in digital forensics and incident response (DFIR).",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 380,
    views: 24500,
    tags: ["documents-metadata", "vba-macros", "office-documents", "oletools", "dfir"]
  },
  {
    name: "PeepDF",
    categorySlug: "documents-metadata",
    url: "https://github.com/jesparza/peepdf",
    description: "Python tool providing an interactive console to explore PDF files and find whether they contain malicious elements.",
    usageContext: "Navigating internal PDF trees, decoding encrypted streams, and executing embedded JavaScript inside a controlled environment.",
    inputOutput: "Input: PDF document | Output: Interactive shell, stream decoders, embedded object identifiers",
    opsecNotes: "Helps analyze weaponized documents safely without opening them in standard readers.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 250,
    views: 16100,
    tags: ["documents-metadata", "peepdf", "pdf-analysis", "interactive-console"]
  },

  // Additional Image & Video tools
  {
    name: "FaceCheck.ID",
    categorySlug: "image-video",
    url: "https://facecheck.id",
    description: "Facial recognition search engine to check a photo of someone against mugshots, registered sex offenders, news, and scammer registries.",
    usageContext: "Investigating suspected romance scammers, identity theft impostors, and verifying suspect arrest records.",
    inputOutput: "Input: Face photo | Output: Confidence matches from criminal databases, news articles, and social profiles",
    opsecNotes: "Provides direct links to source records; verify identities independently.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 410,
    views: 27800,
    tags: ["image-video", "facecheck", "facial-recognition", "mugshots", "scammers"]
  },
  {
    name: "Bing Visual Search",
    categorySlug: "image-video",
    url: "https://www.bing.com/visualsearch",
    description: "Microsoft's visual search engine with object cropping, text recognition, and product identification.",
    usageContext: "Alternative reverse image search often indexing different regional sites than Google and Yandex.",
    inputOutput: "Input: Image or URL | Output: Visually similar pages, object suggestions, extracted text",
    opsecNotes: "Useful cross-reference tool.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 290,
    views: 18700,
    tags: ["image-video", "bing", "visual-search", "crops"]
  },
  {
    name: "Deepware Scanner",
    categorySlug: "image-video",
    url: "https://scanner.deepware.ai",
    description: "AI-based deepfake video detection scanner analyzing video frames for facial manipulation, warping, and synthetic speech.",
    usageContext: "Evaluating whether a viral video of a politician or celebrity is an AI-generated deepfake.",
    inputOutput: "Input: Video URL or file | Output: Deepfake probability score, frame-by-frame anomaly graph",
    opsecNotes: "Continuously updated to counter new generative diffusion models.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 260,
    views: 17200,
    tags: ["image-video", "deepfake", "ai-detection", "video-forensics", "synthetic-media"]
  },

  // Additional Threat Intel tools
  {
    name: "ThreatFox by abuse.ch",
    categorySlug: "threat-intel",
    url: "https://threatfox.abuse.ch",
    description: "Free platform for sharing indicators of compromise (IoCs) associated with malware, C2 servers, and botnets.",
    usageContext: "Downloading fresh C2 server IPs, malicious domain feeds, and payload hashes for SIEM and threat hunting.",
    inputOutput: "Input: Malware tag or IoC query | Output: Associated malware family, confidence level, first seen date",
    opsecNotes: "High-fidelity community data with minimal false positives.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 390,
    views: 25100,
    tags: ["threat-intel", "threatfox", "iocs", "c2-servers", "botnets"]
  },
  {
    name: "Feodo Tracker",
    categorySlug: "threat-intel",
    url: "https://feodotracker.abuse.ch",
    description: "Monitors and tracks active botnet command and control (C2) servers associated with banking trojans and malware families (Dridex, Emotet, QakBot).",
    usageContext: "Validating if an IP is an active botnet controller currently communicating with infected victim PCs.",
    inputOutput: "Input: IP address | Output: Botnet family, C2 status (online/offline), uptime history",
    opsecNotes: "Live tracking of critical banking malware infrastructure.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 330,
    views: 21300,
    tags: ["threat-intel", "feodo-tracker", "botnets", "banking-trojans", "c2"]
  },
  {
    name: "SSL Blacklist (SSLBL)",
    categorySlug: "threat-intel",
    url: "https://sslbl.abuse.ch",
    description: "Project identifying and tracking malicious SSL/TLS certificates used by botnet C2 servers to secure command traffic.",
    usageContext: "Detecting malicious servers by matching SHA1 fingerprints of self-signed SSL certificates.",
    inputOutput: "Input: Certificate SHA1 fingerprint | Output: Associated malware family, C2 IPs using this certificate",
    opsecNotes: "Certificate fingerprint matching reliably tracks malware campaigns across IP migrations.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 280,
    views: 18200,
    tags: ["threat-intel", "ssl-blacklist", "certificates", "fingerprints", "botnet-c2"]
  },

  // Additional Archives tools
  {
    name: "Time Travel Memento Project",
    categorySlug: "archives",
    url: "https://timetravel.mementoweb.org",
    description: "Finds historical versions of web pages across dozens of global web archives (Wayback, national libraries, Internet Memory) at once.",
    usageContext: "Aggregating all global web archives when a page is missing or blocked on the primary Internet Archive.",
    inputOutput: "Input: URL + Target date | Output: Memento list from 20+ national and international digital archives",
    opsecNotes: "Federated search protocol for web archives.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 220,
    views: 14600,
    tags: ["archives", "memento", "federated-archives", "national-libraries"]
  },
  {
    name: "Perma.cc",
    categorySlug: "archives",
    url: "https://perma.cc",
    description: "Developed by the Harvard Law School Library, Perma.cc creates permanent, unalterable web citation links for legal scholars and courts.",
    usageContext: "Preventing 'link rot' in published investigative reports and legal court briefs.",
    inputOutput: "Input: URL | Output: Permanent, tamper-evident archival record with institutional custody",
    opsecNotes: "Recognized by judicial systems and supreme courts as authoritative permanent citations.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 310,
    views: 20100,
    tags: ["archives", "perma-cc", "harvard-law", "legal-citation", "link-rot"]
  },

  // Additional Dark Web tools
  {
    name: "OnionSearch Python Tool",
    categorySlug: "dark-web",
    url: "https://github.com/milo2012/onionsearch",
    description: "Python script that scrapes multiple darknet search engines (Ahmia, Candle, Torch, Not Evil, Haystak) concurrently.",
    usageContext: "Automating dark web searches across multiple search engines from command line.",
    inputOutput: "Input: Search query | Output: CSV/TXT file with aggregated .onion URLs and titles",
    opsecNotes: "Routes requests through local Tor socks5 proxy (127.0.0.1:9050).",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 290,
    views: 18900,
    tags: ["dark-web", "onionsearch", "multi-engine", "python-cli", "tor"]
  },
  {
    name: "DarknetLive News & Guide",
    categorySlug: "dark-web",
    url: "https://darknetlive.com",
    description: "News, verified links, arrest coverage, and technical documentation regarding darknet markets and onion services.",
    usageContext: "Staying informed on market seizures, law enforcement take-downs, and cryptographic key rotations.",
    inputOutput: "Input: Clearnet news portal | Output: In-depth journalism on darknet ecosystem developments",
    opsecNotes: "Reliable clearnet source on dark web law enforcement operations.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 240,
    views: 15700,
    tags: ["dark-web", "darknetlive", "seizures", "news", "markets"]
  },

  // Additional People Search tools
  {
    name: "CyberBackgroundChecks",
    categorySlug: "people-search",
    url: "https://www.cyberbackgroundchecks.com",
    description: "100% free US public records search tool displaying full names, DOB, age, address history, relatives, and aliases.",
    usageContext: "Extremely fast, uncluttered public record lookups without paywalls.",
    inputOutput: "Input: Name, address, or phone | Output: Comprehensive background record with phone numbers and known associates",
    opsecNotes: "Requires US IP address or VPN to access.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 29800,
    tags: ["people-search", "public-records", "free-lookup", "associates", "addresses"]
  },
  {
    name: "SearchBug",
    categorySlug: "people-search",
    url: "https://www.searchbug.com",
    description: "Data broker tool for verifying phone carriers (identifying porting history), SSN validation, and death master file checks.",
    usageContext: "Identifying whether a phone number has been ported between carriers or registered to a virtual number.",
    inputOutput: "Input: Phone number | Output: Carrier name, line type (Wireless/VoIP/Landline), porting date",
    opsecNotes: "Free sample lookups; paid for bulk verification.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.5,
    ratingCount: 210,
    views: 13800,
    tags: ["people-search", "phone-porting", "carrier-lookup", "voip"]
  },

  // Additional Network tools
  {
    name: "Wireshark",
    categorySlug: "network-routing",
    url: "https://www.wireshark.org",
    description: "The world's foremost and widely-used network protocol analyzer, capturing and interactively browsing packet traffic.",
    usageContext: "Inspecting raw PCAP files, analyzing C2 beaconing, extracting TLS handshakes, and decoding malware communication.",
    inputOutput: "Input: Live network interface or .pcap file | Output: Packet-level protocol dissection, stream reconstruction",
    opsecNotes: "The quintessential tool for network forensics.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 890,
    views: 59000,
    tags: ["network-routing", "wireshark", "pcap", "packet-analysis", "essential"]
  },
  {
    name: "CIDR.xyz",
    categorySlug: "network-routing",
    url: "https://cidr.xyz",
    description: "Interactive visual tool to quickly understand and calculate IPv4 CIDR subnet masks and IP ranges.",
    usageContext: "Calculating subnet boundaries, broadcast addresses, and netmasks during network recon and target scope definition.",
    inputOutput: "Input: IP address with CIDR notation (/24, /16) | Output: First/Last host, mask, binary representation",
    opsecNotes: "Fast client-side utility.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 270,
    views: 17300,
    tags: ["network-routing", "cidr", "subnetting", "ip-ranges", "calculator"]
  },

  // Additional Wireless tools
  {
    name: "ADS-B Exchange (Unfiltered)",
    categorySlug: "wireless-rf",
    url: "https://globe.adsbexchange.com",
    description: "The world's largest co-op of unfiltered flight data: does not block military, VIP, or government aircraft tracking.",
    usageContext: "Tracking military reconnaissance aircraft, border patrol surveillance flights, and private jets blocked on commercial apps.",
    inputOutput: "Input: Map coordinate or military filter button (U) | Output: Live aircraft positions, altitude, transponder squawk codes",
    opsecNotes: "Crucial alternative to Flightradar24 for military and investigative reporting.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 610,
    views: 41000,
    tags: ["wireless-rf", "ads-b", "unfiltered", "military-aircraft", "aviation"]
  },
  {
    name: "VesselFinder",
    categorySlug: "wireless-rf",
    url: "https://www.vesselfinder.com",
    description: "Free real-time marine traffic and vessel tracking service powered by extensive terrestrial and satellite AIS networks.",
    usageContext: "Tracking cargo vessels, container ships, tankers, port arrivals, and historical ship routes.",
    inputOutput: "Input: Vessel name or IMO | Output: Real-time map position, speed, port calls history, vessel specs",
    opsecNotes: "Excellent cross-validation against MarineTraffic.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 350,
    views: 22400,
    tags: ["wireless-rf", "vessels", "maritime", "ais", "cargo-ships"]
  }
];
