import { SEED_RESOURCES } from './seedResources.ts';
import { ADDITIONAL_RESOURCES } from './moreSeedResources.ts';
import { SEED_CATEGORIES, SeedCategory, SeedResource } from './seedCategories.ts';

// Extra specialized tools to hit 205+ items across all 16 categories
const EXTRA_RESOURCES: SeedResource[] = [
  // Username extras
  {
    name: "Socialcat Username Radar",
    categorySlug: "username",
    url: "https://socialcat.io",
    description: "Scan emerging alternative social networks (Mastodon, Bluesky, Threads, Nostr) for target handles.",
    usageContext: "Discovering decentralized and federated web accounts.",
    inputOutput: "Input: Handle | Output: Federated web handles, Nostr public keys (npub)",
    opsecNotes: "Decentralized networks publish public keys openly.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 140,
    views: 7800,
    tags: ["username", "fediverse", "mastodon", "nostr", "bluesky"]
  },
  {
    name: "Namevine",
    categorySlug: "username",
    url: "https://namevine.com",
    description: "Multi-service visual availability grid with real-time feedback on top social and video platforms.",
    usageContext: "Assessing brand identity reservations.",
    inputOutput: "Input: Name | Output: Platform statuses",
    opsecNotes: "Client-side queries.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.3,
    ratingCount: 88,
    views: 4900,
    tags: ["username", "social", "lookup"]
  },
  // Email extras
  {
    name: "BreachDirectory",
    categorySlug: "email",
    url: "https://breachdirectory.org",
    description: "Free data breach search allowing security analysts to check if an email or username was compromised with partial hashes.",
    usageContext: "Identifying compromised credentials from breaches without paid enterprise tools.",
    inputOutput: "Input: Email or username | Output: Compromised sources, masked SHA/MD5 hash of password",
    opsecNotes: "Community-driven open breach index.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 210,
    views: 14200,
    tags: ["email", "breach", "hashes", "free"]
  },
  {
    name: "CastrickClues Email Permutator",
    categorySlug: "email",
    url: "https://castrickclues.com",
    description: "Advanced permutation engine generating corporate email variations with automated live SMTP deliverability tests.",
    usageContext: "Generating target email lists when targeting specific executive roles.",
    inputOutput: "Input: Name + domain | Output: 40+ permutations with MX test",
    opsecNotes: "Batch testing can trigger spam defenses; throttle requests.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 120,
    views: 7600,
    tags: ["email", "permutator", "corporate"]
  },
  // Domain extras
  {
    name: "Findomain Subdomain Finder",
    categorySlug: "domain",
    url: "https://github.com/Findomain/Findomain",
    description: "The fastest subdomain enumerator written in Rust, leveraging multiple APIs and certificate transparency engines.",
    usageContext: "High-speed reconnaissance for reconnaissance pipelines.",
    inputOutput: "Input: Domain | Output: Discovered subdomains, IP resolutions, HTTP status",
    opsecNotes: "Can output JSON formatted feeds directly into databases.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 390,
    views: 23400,
    tags: ["domain", "rust", "subdomains", "cli", "fast"]
  },
  {
    name: "Knockpy Subdomain Scanner",
    categorySlug: "domain",
    url: "https://github.com/guelfoweb/knock",
    description: "Python3 tool to enumerate subdomains on a target domain through a wordlist and DNS zone analysis.",
    usageContext: "Discovering unindexed internal hostnames through intelligent dictionary brute-forcing.",
    inputOutput: "Input: Domain name | Output: Resolved hosts, server banners, IP addresses",
    opsecNotes: "Generates high volume of DNS queries to recursive resolvers.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 280,
    views: 16800,
    tags: ["domain", "bruteforce", "dns", "wordlists"]
  },
  {
    name: "Rapid7 Project Sonar (FDNS)",
    categorySlug: "domain",
    url: "https://opendata.rapid7.com/sonar.fdns_v2/",
    description: "Massive open database of forward DNS resolutions collected from nationwide internet internet-wide surveys.",
    usageContext: "Offline querying of billions of historical DNS A, AAAA, and CNAME records.",
    inputOutput: "Input: Root domain | Output: Millions of surveyed historical subdomain mappings",
    opsecNotes: "Downloadable raw dataset; perfect for offline investigations.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 19100,
    tags: ["domain", "sonar", "rapid7", "forward-dns", "big-data"]
  },
  // IP extras
  {
    name: "IP2Location Demo",
    categorySlug: "ip-address",
    url: "https://www.ip2location.com/demo",
    description: "Geolocation lookup identifying IP country, region, city, coordinates, zip code, time zone, ISP, domain, and usage type.",
    usageContext: "Secondary validation of IP geographic location and connection category (residential vs datacenter).",
    inputOutput: "Input: IP address | Output: Location, ASN, ISP, weather station ID, mobile carrier",
    opsecNotes: "Passive query against commercial GeoIP database.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 230,
    views: 14500,
    tags: ["ip-address", "ip2location", "isp", "usage-type"]
  },
  {
    name: "Criminal IP Asset Search",
    categorySlug: "ip-address",
    url: "https://www.criminalip.io",
    description: "Cyber threat intelligence search engine specializing in asset search, vulnerability scanning, and phishing link detection.",
    usageContext: "Scoring risk and finding open ports, exposed RDP connections, and phishing domains.",
    inputOutput: "Input: IP or domain | Output: Inbound/Outbound risk score, open ports, connected banners",
    opsecNotes: "Provides 50 free searches per month upon registration.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 290,
    views: 18100,
    tags: ["ip-address", "threat-intel", "cyber-risk", "ports"]
  },
  {
    name: "Shadowserver Dashboard",
    categorySlug: "ip-address",
    url: "https://dashboard.shadowserver.org",
    description: "Non-profit security organization conducting daily internet-wide scans for exposed industrial controllers, malware infections, and vulnerabilities.",
    usageContext: "Tracking nationwide vulnerability counts and botnet infections across countries and ASNs.",
    inputOutput: "Input: Country or ASN | Output: Statistics on infected bot hosts, exposed Telnet/SSH, vulnerable services",
    opsecNotes: "Public dashboard tracking global cyber hygiene.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 240,
    views: 15300,
    tags: ["ip-address", "shadowserver", "botnet-stats", "hygiene"]
  },
  // Social Media extras
  {
    name: "TweetDeck / X Pro (Workarounds)",
    categorySlug: "social-media",
    url: "https://tweetdeck.twitter.com",
    description: "Multi-column real-time streaming dashboard for Twitter/X monitoring lists, keywords, and geographic search filters.",
    usageContext: "Live monitoring of multiple search queries and emergency hashtags simultaneously during crisis response.",
    inputOutput: "Input: Column search queries | Output: Real-time multi-column live feed",
    opsecNotes: "Now requires X Premium subscription; use OSS alternatives like FeedDeck for RSS/Mastodon.",
    toolFlags: "R",
    isFree: 0,
    ratingAvg: 4.5,
    ratingCount: 380,
    views: 22000,
    tags: ["social-media", "dashboard", "live-monitoring", "multi-column"]
  },
  {
    name: "Bluesky Firehose Explorer",
    categorySlug: "social-media",
    url: "https://bsky.app",
    description: "Open AT Protocol decentralized network with public firehose API stream of all posts, reposts, and profile updates.",
    usageContext: "Real-time surveillance of decentralized conversations and sentiment without API gatekeeping.",
    inputOutput: "Input: Keyword or DID identifier | Output: Public firehose websocket events and user profiles",
    opsecNotes: "AT Protocol is 100% public by design; all records are cryptographically signed.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 270,
    views: 16900,
    tags: ["social-media", "bluesky", "at-protocol", "firehose", "decentralized"]
  },
  // Geolocation extras
  {
    name: "OpenStreetMap Nominatim",
    categorySlug: "geolocation",
    url: "https://nominatim.openstreetmap.org",
    description: "Open-source geocoding and reverse-geocoding engine searching OSM data by name and address or coordinates.",
    usageContext: "Converting latitude/longitude coordinates into administrative boundary names and street addresses.",
    inputOutput: "Input: Lat/Long or Address text | Output: Structured address breakdown (country, state, county, suburb, road)",
    opsecNotes: "Open data free from commercial tracking; subject to fair use limits.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 340,
    views: 21200,
    tags: ["geolocation", "osm", "reverse-geocoding", "open-data"]
  },
  {
    name: "Zoom Earth Live Weather & Satellite",
    categorySlug: "geolocation",
    url: "https://zoom.earth",
    description: "Near real-time live satellite images, rain radar maps, and hurricane tracker updated every 10-15 minutes.",
    usageContext: "Tracking typhoons, cloud patterns, and verifying atmospheric weather conditions during critical events.",
    inputOutput: "Input: Location pin | Output: High-definition animated weather radar and true-color satellite loop",
    opsecNotes: "Very fast browser-based interface for rapid meteorological verification.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 450,
    views: 28700,
    tags: ["geolocation", "satellite", "radar", "hurricanes", "real-time"]
  },
  // Search Dorks extras
  {
    name: "Pastebin Dump Search (psbdmp)",
    categorySlug: "search-dorks",
    url: "https://psbdmp.ws",
    description: "Search engine indexing Pastebin and other text dump repositories for leaked database credentials, code, and logs.",
    usageContext: "Finding plaintext dumps containing target email addresses, server passwords, or internal configurations.",
    inputOutput: "Input: Keyword / email | Output: Historical paste links with timestamps and content snippet",
    opsecNotes: "Pastes may be removed from original Pastebin but remain preserved in archive caches.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 19400,
    tags: ["search-dorks", "pastebin", "dumps", "credentials", "leaks"]
  },
  {
    name: "Advantage Google Dork Builder",
    categorySlug: "search-dorks",
    url: "https://github.com/BullsEye0/google_dork_list",
    description: "Comprehensive categorized collection of Google dorks for discovering SQL injections, open directories, and cameras.",
    usageContext: "Finding publicly accessible directory listings (Index of /) on target infrastructure.",
    inputOutput: "Input: Domain + dork category | Output: 'intitle:\"index of\" \"parent directory\" target.com'",
    opsecNotes: "Uncovers files exposed by misconfigured Apache/Nginx web server directory browsing.",
    toolFlags: "D",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 290,
    views: 18100,
    tags: ["search-dorks", "index-of", "directory-traversal", "dork-collection"]
  },
  // Public Records extras
  {
    name: "Foreign Agents Registration Act (FARA)",
    categorySlug: "public-records",
    url: "https://www.justice.gov/nsd-fara",
    description: "US Department of Justice database of registered foreign agents lobbying the United States on behalf of foreign powers.",
    usageContext: "Tracing foreign state influence, propaganda funding, lobbying contracts, and political consultant payments.",
    inputOutput: "Input: Foreign principal or lobbyist name | Output: Sworn registration statements, financial payments, meeting logs",
    opsecNotes: "Authoritative United States Department of Justice public records.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 250,
    views: 16200,
    tags: ["public-records", "fara", "foreign-agents", "lobbying", "doj"]
  },
  {
    name: "Delaware Corporate Registry Search",
    categorySlug: "public-records",
    url: "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
    description: "Search corporate entities incorporated in Delaware, the primary domestic jurisdiction for American LLCs and corporations.",
    usageContext: "Validating incorporation status, registered agent address, and file number for Delaware entities.",
    inputOutput: "Input: Company name or File number | Output: Entity type, incorporation date, registered agent name",
    opsecNotes: "Delaware does not publicly list corporate directors; pair with SEC filings or litigation dockets.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 280,
    views: 17900,
    tags: ["public-records", "delaware", "llc", "incorporation", "shell-companies"]
  },
  // Documents extras
  {
    name: "Binwalk Firmware Analysis",
    categorySlug: "documents-metadata",
    url: "https://github.com/ReFirmLabs/binwalk",
    description: "Fast, easy-to-use tool for analyzing, reverse engineering, and extracting firmware images and embedded file systems.",
    usageContext: "Carving hidden archives, certificates, and hardcoded private keys out of binary files and IoT camera firmware.",
    inputOutput: "Input: Binary firmware or file | Output: Extracted file systems (SquashFS, CramFS), embedded certificates",
    opsecNotes: "Essential for hardware hacking and supply chain security investigations.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 390,
    views: 24200,
    tags: ["documents-metadata", "binwalk", "firmware", "carving", "reverse-engineering"]
  },
  {
    name: "Strings (GNU Coreutils)",
    categorySlug: "documents-metadata",
    url: "https://www.gnu.org/software/coreutils/",
    description: "Standard Unix command that prints the sequences of printable characters in files, revealing hardcoded URLs and secrets.",
    usageContext: "Instantly scanning unknown compiled binaries or corrupted documents for human-readable URLs, IPs, and passwords.",
    inputOutput: "Input: Any file | Output: List of printable strings of at least 4 characters",
    opsecNotes: "Classic, reliable first step in any file triage pipeline.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 320,
    views: 20100,
    tags: ["documents-metadata", "strings", "cli", "triage", "classic"]
  },
  // Image & Video extras
  {
    name: "Baidu Reverse Image Search",
    categorySlug: "image-video",
    url: "https://image.baidu.com",
    description: "China's leading visual search engine with unrivaled image indexation across WeChat, Weibo, and Chinese domains.",
    usageContext: "Locating image origins for photos captured or published within Chinese cyberspace.",
    inputOutput: "Input: Image file | Output: Matching web pages across Chinese internet ecosystems",
    opsecNotes: "Submitting images to Baidu is logged in Chinese search infrastructure; use VPN/proxy.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 280,
    views: 18400,
    tags: ["image-video", "baidu", "china-osint", "reverse-image", "weibo"]
  },
  {
    name: "Picflow EXIF Inspector",
    categorySlug: "image-video",
    url: "https://picflow.com/exif-viewer",
    description: "Clean visual web app showing photo EXIF tags, shutter speed, ISO, color profile, and embedded GPS map.",
    usageContext: "Rapid visual review of professional photography settings and lens models in the browser.",
    inputOutput: "Input: JPG/TIFF/PNG photo | Output: Card layout of camera hardware specs and GPS location",
    opsecNotes: "Client-side processing maintains privacy of uploaded photo.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 160,
    views: 10800,
    tags: ["image-video", "exif", "camera-specs", "gps"]
  },
  // Threat Intel extras
  {
    name: "Joe Sandbox Community",
    categorySlug: "threat-intel",
    url: "https://www.joesandbox.com",
    description: "Deep malware analysis engine running on Windows, macOS, Android, and iOS with deep behavioral detonation reports.",
    usageContext: "Automated analysis of complex malware evasions, anti-VM checks, and C2 traffic decryptors.",
    inputOutput: "Input: File / URL | Output: Multi-OS execution report, MITRE matrix, evasion detection",
    opsecNotes: "Community analyses are publicly searchable.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 370,
    views: 23600,
    tags: ["threat-intel", "joe-sandbox", "malware", "behavioral-analysis", "mitre"]
  },
  {
    name: "Hatching Triage Sandbox",
    categorySlug: "threat-intel",
    url: "https://tria.ge",
    description: "High-volume malware analysis sandbox providing interactive browser access, video replay, and config extractors.",
    usageContext: "Extracting C2 configuration files, decrypted passwords, and bot IDs from active malware families.",
    inputOutput: "Input: Executable or document | Output: Extracted botnet config, C2 server list, video replay",
    opsecNotes: "Renowned for automated family configuration extraction.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 19800,
    tags: ["threat-intel", "triage", "config-extractor", "sandbox", "malware"]
  },
  // Archives extras
  {
    name: "OldWeb.today",
    categorySlug: "archives",
    url: "https://oldweb.today",
    description: "Emulates vintage web browsers (Mosaic, Netscape Navigator 3, IE 4) to view historical web pages with era-accurate rendering.",
    usageContext: "Viewing historical 1990s web pages that require deprecated plugins (Flash, RealPlayer, Shockwave) inside an emulated browser.",
    inputOutput: "Input: Target URL + Browser year | Output: Interactive container session running legacy Netscape/IE",
    opsecNotes: "Fascinating platform for viewing web history in its original technological context.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 220,
    views: 14500,
    tags: ["archives", "emulation", "vintage-web", "netscape", "historical-rendering"]
  },
  {
    name: "UK Web Archive",
    categorySlug: "archives",
    url: "https://www.webarchive.org.uk",
    description: "Collects millions of websites published in the UK since 2004, preserving national heritage and public government records.",
    usageContext: "Investigating defunct British organizations, charities, and political campaign web pages.",
    inputOutput: "Input: UK URL or subject | Output: Curated national archive snapshots",
    opsecNotes: "Maintained by the British Library and national institutions.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 180,
    views: 11900,
    tags: ["archives", "uk-archive", "british-library", "historical-records"]
  },
  // Dark Web extras
  {
    name: "Haystak Darknet Search",
    categorySlug: "dark-web",
    url: "https://haystak.co",
    description: "Claims to index over 1.5 billion dark web pages across thousands of hidden services with historical cache snapshots.",
    usageContext: "Searching for obscure .onion forums, historical market products, and researcher blogs.",
    inputOutput: "Input: Keyword / selector | Output: Ranked .onion search results",
    opsecNotes: "Offers both clearnet preview and direct .onion navigation.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.5,
    ratingCount: 240,
    views: 15400,
    tags: ["dark-web", "haystak", "onion-search", "hidden-services"]
  },
  {
    name: "Torch Darknet Search Engine",
    categorySlug: "dark-web",
    url: "http://torchdeedp3i2jigzjdmfpn5ttjhthh5wbmda2rr3jvqjg5p77c54dqd.onion",
    description: "One of the oldest and longest continuously operating search engines on the Tor network, indexing over 400,000 onion pages.",
    usageContext: "Discovering deep-web discussions and uncensored forums directly via Tor Browser.",
    inputOutput: "Input: Query inside Tor | Output: Plaintext list of matching .onion pages",
    opsecNotes: "Must be accessed through Tor Browser; contains uncensored search results.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 310,
    views: 20500,
    tags: ["dark-web", "torch", "oldest-onion-engine", "uncensored"]
  },
  // People Search extras
  {
    name: "USPhoneBook",
    categorySlug: "people-search",
    url: "https://www.usphonebook.com",
    description: "Free reverse phone lookup tool providing caller name, carrier, address, and known relatives for US phone numbers.",
    usageContext: "Quick triage of incoming unknown or scam phone numbers.",
    inputOutput: "Input: 10-digit phone number | Output: Owner name, current address, past address history, relatives",
    opsecNotes: "100% free with no credit card required.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 380,
    views: 24300,
    tags: ["people-search", "reverse-phone", "us-phone", "relatives", "free"]
  },
  {
    name: "Nuwber People Finder",
    categorySlug: "people-search",
    url: "https://nuwber.com",
    description: "Comprehensive public records aggregator compiling contact details, property values, and family connections across the US.",
    usageContext: "Gathering property ownership and estimated home valuation for background dossiers.",
    inputOutput: "Input: Name + City or Address | Output: Public contact record, property deed summary",
    opsecNotes: "Freemium preview available for basic verification.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.4,
    ratingCount: 220,
    views: 14100,
    tags: ["people-search", "nuwber", "property-records", "phone-lookup"]
  },
  // Network Infrastructure extras
  {
    name: "Subdomain Center",
    categorySlug: "network-routing",
    url: "https://api.subdomain.center",
    description: "Fast public API providing instant subdomain enumeration aggregated from certificate transparency and passive DNS caches.",
    usageContext: "Programmatically retrieving all known subdomains for any root domain without rate limits.",
    inputOutput: "Input: Domain name | Output: JSON array of discovered subdomains",
    opsecNotes: "Clean JSON API easy to integrate into custom intelligence scripts.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 260,
    views: 16700,
    tags: ["network-routing", "subdomain-center", "json-api", "fast"]
  },
  {
    name: "PeeringDB Search API",
    categorySlug: "network-routing",
    url: "https://www.peeringdb.com/api/net",
    description: "Direct REST API to query network ASN peering policies, router interface speeds, and point-of-presence (PoP) coordinates.",
    usageContext: "Extracting precise telecom carrier interconnect maps and physical data center rack locations.",
    inputOutput: "Input: ASN number | Output: Full peering policy, IXP connections, contact emails",
    opsecNotes: "Official open API for PeeringDB.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 310,
    views: 19500,
    tags: ["network-routing", "peeringdb", "api", "ixp", "datacenter"]
  },
  // Wireless extras
  {
    name: "SDR.hu WebSDR Network",
    categorySlug: "wireless-rf",
    url: "http://sdr.hu",
    description: "Directory of globally distributed KiwiSDR wideband shortwave radio receivers covering 0-30 MHz.",
    usageContext: "Triangulating radio transmissions using TDoA (Time Difference of Arrival) across multiple synchronized SDR receivers.",
    inputOutput: "Input: Frequency + multi-station TDoA tool | Output: Geographic hyperbola map pin locating radio transmitter",
    opsecNotes: "TDoA radio direction finding can pinpoint the physical location of HF transmitters anywhere on Earth.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 460,
    views: 31200,
    tags: ["wireless-rf", "kiwisdr", "tdoa", "radio-direction-finding", "shortwave"]
  },
  {
    name: "CellMapper.net",
    categorySlug: "wireless-rf",
    url: "https://www.cellmapper.net",
    description: "Crowd-sourced cellular tower and coverage map showing 2G/3G/4G LTE/5G base stations, sector azimuths, and signal contours.",
    usageContext: "Analyzing cell tower antenna directionality (bearing/azimuth) to triangulate phone connections.",
    inputOutput: "Input: Mobile provider + MCC/MNC | Output: Map with exact cell tower locations and antenna broadcast wedges",
    opsecNotes: "Provides antenna bearing angles for radio signal analysis.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 390,
    views: 24700,
    tags: ["wireless-rf", "cellmapper", "5g", "lte-towers", "antenna-azimuth"]
  }
];

export const ALL_SEED_RESOURCES: SeedResource[] = [
  ...SEED_RESOURCES,
  ...ADDITIONAL_RESOURCES,
  ...EXTRA_RESOURCES
];
