import { SeedResource } from './seedCategories.ts';

export const SEED_RESOURCES: SeedResource[] = [
  // --- 1. USERNAME INTELLIGENCE ---
  {
    name: "Sherlock Project",
    categorySlug: "username",
    url: "https://github.com/sherlock-project/sherlock",
    description: "Hunt down social media accounts by username across over 400+ popular websites, forums, and networks.",
    usageContext: "Initial target reconnaissance to map a target's online presence across multiple platforms simultaneously.",
    inputOutput: "Input: Target username handle | Output: Active profile URLs, account existence confirmations",
    opsecNotes: "Runs CLI requests directly from your host IP. Use with Tor proxy or rotating VPN to avoid rate limiting and IP leakage.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 342,
    views: 18450,
    tags: ["username", "cli", "social-media", "cross-platform"]
  },
  {
    name: "WhatsMyName Web",
    categorySlug: "username",
    url: "https://whatsmyname.app",
    description: "Fast, web-based username enumeration tool querying 500+ curated platforms with real-time response checks.",
    usageContext: "Rapid browser-based username triage without requiring Python or terminal environment setup.",
    inputOutput: "Input: Username string | Output: List of verified profile URLs with HTTP 200 checks",
    opsecNotes: "Queries are dispatched from client/backend proxy. Avoid entering confidential or classified target handles directly.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 289,
    views: 14210,
    tags: ["username", "web-tool", "osint-framework", "enumeration"]
  },
  {
    name: "Namechk",
    categorySlug: "username",
    url: "https://namechk.com",
    description: "Check username and domain availability across dozens of major social networks and top-level domains.",
    usageContext: "Discover where a pseudonym has or has not been claimed to evaluate persona consistency.",
    inputOutput: "Input: Desired username | Output: Available vs. taken status across social platforms and TLDs",
    opsecNotes: "Commercial service; searches may be logged or monetized for domain suggestions.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.3,
    ratingCount: 165,
    views: 9200,
    tags: ["username", "domains", "social-checker", "freemium"]
  },
  {
    name: "Blackbird OSINT",
    categorySlug: "username",
    url: "https://github.com/p1ngul1n0/blackbird",
    description: "High-speed Python command-line OSINT tool to search target accounts by username across 500+ platforms with metadata extraction.",
    usageContext: "Advanced username enumeration that also attempts to scrape profile pictures and bio summaries where available.",
    inputOutput: "Input: Username string | Output: Platform links, response status, profile metadata",
    opsecNotes: "Generates high volume of outbound HTTP requests. Route through socks5 proxy for anonymity.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 198,
    views: 8740,
    tags: ["username", "cli", "python", "scraping"]
  },
  {
    name: "Maigret",
    categorySlug: "username",
    url: "https://github.com/soxoj/maigret",
    description: "Generate comprehensive dossier on a username: scans 2500+ sites, parses user IDs, names, links, and avatar hashes.",
    usageContext: "In-depth intelligence collection when tracking persistent online handles and criminal pseudonyms.",
    inputOutput: "Input: Handle name | Output: HTML/PDF report with cross-referenced identities, bio text, and user IDs",
    opsecNotes: "Heavy footprint; downloads profile avatars. Execute strictly inside an isolated research virtual machine.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 310,
    views: 15300,
    tags: ["username", "dossier", "avatar-hash", "in-depth"]
  },
  {
    name: "UserSearch.org",
    categorySlug: "username",
    url: "https://usersearch.org",
    description: "Reverse search usernames, emails, and phone numbers across dating websites, forums, crypto networks, and chat services.",
    usageContext: "Locating secondary profiles often hidden from standard social networks, particularly forums and dating platforms.",
    inputOutput: "Input: Username handle | Output: Direct profile links categorized by site category",
    opsecNotes: "Rate limits apply on free tier. Third-party trackers present; utilize privacy shields.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.2,
    ratingCount: 112,
    views: 6420,
    tags: ["username", "forums", "dating-sites", "crypto"]
  },
  {
    name: "Instant Username Search",
    categorySlug: "username",
    url: "https://instantusername.com",
    description: "As-you-type client-side username checker across 100+ mainstream and niche communities.",
    usageContext: "Quick sanity checks during interviews or time-critical investigative leads.",
    inputOutput: "Input: Live keystrokes | Output: Color-coded green/red grid indicating profile presence",
    opsecNotes: "Client-side AJAX requests emit from user browser directly to external targets.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 88,
    views: 5120,
    tags: ["username", "instant", "lightweight", "client-side"]
  },
  {
    name: "CheckUsernames",
    categorySlug: "username",
    url: "https://checkusernames.com",
    description: "Verifies the presence of a specific username across over 160 top social platforms with immediate status indicators.",
    usageContext: "Quick broad assessment of whether a brand name or personal handle is registered globally.",
    inputOutput: "Input: Username | Output: Checked matrix of registered web profiles",
    opsecNotes: "Safe passive lookup handled server-side by the provider.",
    toolFlags: "M",
    isFree: 1,
    ratingAvg: 4.1,
    ratingCount: 74,
    views: 4300,
    tags: ["username", "branding", "verification"]
  },
  {
    name: "KnowEm",
    categorySlug: "username",
    url: "https://knowem.com",
    description: "Search brand names, trademarks, and personal usernames across 500+ social networks, domain extensions, and USPTO database.",
    usageContext: "Corporate intelligence and brand infringement investigations.",
    inputOutput: "Input: Brand or username | Output: Multi-category availability report and USPTO trademark check",
    opsecNotes: "Monitors search queries for commercial brand-protection leads.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.0,
    ratingCount: 62,
    views: 3890,
    tags: ["username", "corporate", "trademarks", "uspto"]
  },
  {
    name: "Social-Searcher",
    categorySlug: "username",
    url: "https://www.social-searcher.com",
    description: "Free real-time social media search engine monitoring keywords, user handles, hashtags, and sentiment.",
    usageContext: "Monitoring recent activity, mentions, and posts for a particular target username.",
    inputOutput: "Input: Username or keyword | Output: Stream of social posts, sentiment score, active hours",
    opsecNotes: "Public data aggregation; rate limits without API key.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.5,
    ratingCount: 140,
    views: 7900,
    tags: ["username", "sentiment", "social-monitoring", "real-time"]
  },
  {
    name: "Lullar",
    categorySlug: "username",
    url: "https://com.lullar.com",
    description: "Search people and usernames across major social media directories, blogs, and public forums.",
    usageContext: "Finding legacy profile links and forgotten accounts created in the 2000s and 2010s.",
    inputOutput: "Input: Username or full name | Output: Direct links to personal web spaces",
    opsecNotes: "Passive directory query.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.2,
    ratingCount: 53,
    views: 3100,
    tags: ["username", "legacy", "directories"]
  },
  {
    name: "IDCrawl",
    categorySlug: "username",
    url: "https://www.idcrawl.com",
    description: "Free people search engine scanning public social media profiles, web mentions, and public records for usernames and names.",
    usageContext: "Aggregating public web footprint of an individual from multiple social ecosystems.",
    inputOutput: "Input: Name or handle | Output: Aggregate preview of linked social profiles and images",
    opsecNotes: "Utilizes third-party data broker aggregations.",
    toolFlags: "M",
    isFree: 1,
    ratingAvg: 4.3,
    ratingCount: 97,
    views: 5800,
    tags: ["username", "people-search", "aggregations"]
  },
  {
    name: "PeekYou",
    categorySlug: "username",
    url: "https://www.peekyou.com",
    description: "Finds people online by username, name, or phone number, cross-indexing social networks, news articles, and public blogs.",
    usageContext: "Connecting an anonymous username to a real-world geographic location or full legal name.",
    inputOutput: "Input: Username or Real Name | Output: Discovered social handles, estimated age, city/state",
    opsecNotes: "Subject to US consumer records regulations; IP logged.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 135,
    views: 6920,
    tags: ["username", "identity", "cross-reference"]
  },

  // --- 2. EMAIL ADDRESS ANALYSIS ---
  {
    name: "Have I Been Pwned",
    categorySlug: "email",
    url: "https://haveibeenpwned.com",
    description: "The premier breach lookup service indexing billions of compromised accounts across thousands of historical security breaches.",
    usageContext: "Determine if a subject's email was involved in known public data breaches and which services were compromised.",
    inputOutput: "Input: Email address | Output: List of breaches (dates, data classes exposed, descriptions)",
    opsecNotes: "Troy Hunt's service; does not expose passwords publicly. Direct queries do not compromise target credentials.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 512,
    views: 29800,
    tags: ["email", "breach", "credentials", "essential"]
  },
  {
    name: "Hunter.io",
    categorySlug: "email",
    url: "https://hunter.io",
    description: "Find email addresses associated with any company domain name, discovering naming patterns and verified contacts.",
    usageContext: "Corporate investigations to identify employees, executive emails, and standard corporate email syntax ({f}{last}@domain.com).",
    inputOutput: "Input: Company domain | Output: Verified email addresses, confidence scores, and source URLs",
    opsecNotes: "Free tier offers 25 searches/month. Commercial account required for high-volume sweeps.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 380,
    views: 21400,
    tags: ["email", "corporate", "domain-search", "pattern-analysis"]
  },
  {
    name: "Epieos",
    categorySlug: "email",
    url: "https://epieos.com",
    description: "Reverse email and phone lookup tool to find connected Google accounts, Google Maps reviews, calendars, and gravatars without notifying target.",
    usageContext: "Priceless for extracting target Google Account ID (GaiaID), verified profile picture, and Google Maps public review history.",
    inputOutput: "Input: Email address | Output: Google Profile, Google Maps Reviews, Duolingo, Skype, Gravatar presence",
    opsecNotes: "Totally passive lookup from public APIs; does not ping or alert target inboxes.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 420,
    views: 24800,
    tags: ["email", "google-account", "maps-reviews", "passive"]
  },
  {
    name: "EmailRep.io",
    categorySlug: "email",
    url: "https://emailrep.io",
    description: "Query email reputation and risk metrics: account age, deliverability, domain credibility, and social footprint.",
    usageContext: "Evaluating whether an email address is a disposable burner, newly registered fraud account, or aged legitimate persona.",
    inputOutput: "Input: Email string | Output: Reputation score, credentials leak status, domain age, blacklists",
    opsecNotes: "Free REST API available for automated script pipelines.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 178,
    views: 11200,
    tags: ["email", "reputation", "risk-scoring", "disposable-check"]
  },
  {
    name: "DeHashed",
    categorySlug: "email",
    url: "https://www.dehashed.com",
    description: "Massive cyber threat intelligence and breach search engine indexing leaked credentials, usernames, IPs, and cryptographic hashes.",
    usageContext: "Tracing compromised credentials, historical passwords, and cross-indexing username/email linkages from data leaks.",
    inputOutput: "Input: Email, username, or IP | Output: Breached records, hash types, partial leaked plaintext credentials",
    opsecNotes: "Strict ToS; requires payment for viewing full sensitive decrypted credentials.",
    toolFlags: "R",
    isFree: 0,
    ratingAvg: 4.8,
    ratingCount: 290,
    views: 19500,
    tags: ["email", "breach", "dehashed", "password-hashes"]
  },
  {
    name: "MailboxValidator",
    categorySlug: "email",
    url: "https://www.mailboxvalidator.com",
    description: "Performs deep SMTP MX checks, syntax validation, catch-all server detection, and disposable domain filtering.",
    usageContext: "Verifying whether an email address genuinely exists on the remote mail server without sending an actual message.",
    inputOutput: "Input: Target email | Output: Deliverability status, MX server connection result, temporary email flag",
    opsecNotes: "Sends SMTP RCPT TO handshake to the target server; IP may be logged in target mail server auth logs.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.4,
    ratingCount: 95,
    views: 6100,
    tags: ["email", "smtp-check", "deliverability", "mx"]
  },
  {
    name: "Skymem",
    categorySlug: "email",
    url: "https://www.skymem.info",
    description: "Database of business email addresses indexed from public corporate websites and domain registrars.",
    usageContext: "Discovering email contacts and organizational hierarchy for mid-sized organizations.",
    inputOutput: "Input: Corporate domain | Output: List of associated public email addresses",
    opsecNotes: "Passive database query.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.3,
    ratingCount: 82,
    views: 5400,
    tags: ["email", "corporate-contacts", "domain-indexer"]
  },
  {
    name: "MXToolbox Email Health",
    categorySlug: "email",
    url: "https://mxtoolbox.com/emailhealth",
    description: "Complete email server diagnostic testing SPF records, DKIM signatures, DMARC alignment, and DNS blacklists.",
    usageContext: "Investigating spoofed emails, phishing campaigns, and analyzing sender domain authenticity.",
    inputOutput: "Input: Domain name | Output: SPF/DKIM/DMARC health score, blacklist appearances",
    opsecNotes: "Safe passive lookup querying DNS records and blacklist public endpoints.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 210,
    views: 13900,
    tags: ["email", "spf", "dkim", "dmarc", "anti-phishing"]
  },
  {
    name: "IntelX Email Search",
    categorySlug: "email",
    url: "https://intelx.io",
    description: "Intelligence X search engine indexing paste sites, darknet forums, document dumps, and historical WHOIS records for email addresses.",
    usageContext: "Searching for mentions of an email address across dark web leaks, Pastebin, and government document dumps.",
    inputOutput: "Input: Email selector | Output: Raw paste records, leak dumps, file hashes",
    opsecNotes: "Comprehensive indexing; search results may contain sensitive or illicit breach material.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 360,
    views: 22800,
    tags: ["email", "intelx", "darknet-leaks", "paste-dumps"]
  },
  {
    name: "Email Permutator",
    categorySlug: "email",
    url: "http://emailpermutator.com",
    description: "Generates permutations of potential corporate and personal email addresses based on first name, last name, and target domain.",
    usageContext: "Creating a candidate list of email addresses to test against SMTP verifiers when investigating an individual.",
    inputOutput: "Input: First name, Last name, Domain | Output: 30+ standardized email format variations",
    opsecNotes: "Local client-side calculation; safe to run locally.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 110,
    views: 7400,
    tags: ["email", "permutator", "wordlist", "recon"]
  },
  {
    name: "Verifalia",
    categorySlug: "email",
    url: "https://verifalia.com/validate-email",
    description: "Real-time email verification service that checks mailbox existence, syntax, DNS MX records, and honeypot risk.",
    usageContext: "Confirming if high-profile addresses are active mailboxes without bounce-back emails.",
    inputOutput: "Input: Single email | Output: Quality score, deliverable/undeliverable flag, mailbox full status",
    opsecNotes: "Performs SMTP probe.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.3,
    ratingCount: 78,
    views: 4800,
    tags: ["email", "verification", "smtp", "honeypot"]
  },
  {
    name: "Hudson Rock Cavalier",
    categorySlug: "email",
    url: "https://cavalier.hudsonrock.com",
    description: "Search corporate and personal email domains against compromised infostealer malware logs (RedLine, Raccoon, Vidar).",
    usageContext: "Detecting active credential compromises resulting from modern infostealer infections rather than legacy breaches.",
    inputOutput: "Input: Domain or Email | Output: Count of infected computers, employee vs. client compromises, malware families",
    opsecNotes: "Highly actionable threat intelligence on fresh malware infections.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 195,
    views: 12600,
    tags: ["email", "infostealers", "threat-intel", "malware-logs"]
  },

  // --- 3. DOMAIN & DNS INVESTIGATION ---
  {
    name: "SecurityTrails",
    categorySlug: "domain",
    url: "https://securitytrails.com",
    description: "Total visibility into current and historical DNS records, historical WHOIS, and comprehensive subdomain enumeration.",
    usageContext: "Tracing previous IP hosting infrastructure, historical domain owners before privacy guards, and discovering shadow assets.",
    inputOutput: "Input: Target domain | Output: Historical A/AAAA/MX/NS/TXT records, subdomains, WHOIS timeline",
    opsecNotes: "Requires free account for basic searches; API queries are logged.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 440,
    views: 26500,
    tags: ["domain", "dns", "historical-dns", "whois", "subdomains"]
  },
  {
    name: "DNSDumpster",
    categorySlug: "domain",
    url: "https://dnsdumpster.com",
    description: "Domain research tool that maps out organizational attack surface, discovering hosts, DNS servers, MX servers, and network diagrams.",
    usageContext: "Initial domain reconnaissance and creating visual infrastructure network maps.",
    inputOutput: "Input: Root domain | Output: Subdomain tables, IP geolocations, HTTP headers, visual Excel/PNG graph",
    opsecNotes: "Passive queries against public zone records and open databases.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 395,
    views: 23100,
    tags: ["domain", "recon", "mapping", "subdomain-finder"]
  },
  {
    name: "crt.sh (Certificate Search)",
    categorySlug: "domain",
    url: "https://crt.sh",
    description: "Search Certificate Transparency logs for any domain name to identify newly and historically issued SSL/TLS certificates.",
    usageContext: "Uncovering hidden staging environments, unlinked subdomains (e.g. dev-internal.target.com), and internal hostnames.",
    inputOutput: "Input: %.domain.com wildcard | Output: All public SSL certificates issued, valid dates, SANs (Subject Alternative Names)",
    opsecNotes: "Query public CT logs directly. Completely undetectable by the target domain owner.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 480,
    views: 28900,
    tags: ["domain", "certificates", "subdomains", "ct-logs", "passive"]
  },
  {
    name: "ViewDNS.info",
    categorySlug: "domain",
    url: "https://viewdns.info",
    description: "Swiss-army knife of DNS and domain investigations: Reverse IP lookup, Reverse WHOIS, Port scanner, Traceroute, and DNS propagation.",
    usageContext: "Finding all websites sharing a specific IP or finding all domains registered with a single email address.",
    inputOutput: "Input: IP, Domain, or Email | Output: Reverse IP lists, historical records, traceroute nodes",
    opsecNotes: "Web-based utility; some active tests (port scan) originate from ViewDNS server IPs.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 18400,
    tags: ["domain", "reverse-whois", "reverse-ip", "toolbox"]
  },
  {
    name: "OWASP Amass",
    categorySlug: "domain",
    url: "https://github.com/owasp-amass/amass",
    description: "In-depth network mapping of attack surfaces and external asset discovery using open-source information and active reconnaissance.",
    usageContext: "Industry standard for penetration testers and red teams mapping complex enterprise domain footprints.",
    inputOutput: "Input: Domain / ASN | Output: Comprehensive topology graph of subdomains, IPs, and routing paths",
    opsecNotes: "Can run in passive mode (-passive) to prevent active connections to target assets.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 350,
    views: 21000,
    tags: ["domain", "owasp", "recon", "attack-surface", "cli"]
  },
  {
    name: "BuiltWith",
    categorySlug: "domain",
    url: "https://builtwith.com",
    description: "Web technology profiler revealing frameworks, CMS, advertising tags, analytics trackers (Google Analytics UA/G-IDs), and hosting.",
    usageContext: "Pivot investigations by connecting multiple unrelated websites that share the same Google Analytics or AdSense ID.",
    inputOutput: "Input: Website URL | Output: Complete tech stack profile, shared tracker IDs, historical hosting providers",
    opsecNotes: "Tracker pivoting is one of the most powerful OSINT techniques for attribution.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 290,
    views: 17200,
    tags: ["domain", "tech-stack", "analytics-pivot", "attribution"]
  },
  {
    name: "URLScan.io",
    categorySlug: "domain",
    url: "https://urlscan.io",
    description: "Free service that analyzes websites: records HTTP transactions, DOM snapshots, screenshot renderings, IPs, and TLS certificates.",
    usageContext: "Safely inspect malicious or suspicious URLs in a sandboxed browser environment without visiting them directly.",
    inputOutput: "Input: URL or domain | Output: High-res screenshot, DOM dump, outgoing requests, hashes, ASN contacts",
    opsecNotes: "Public scans are visible to other researchers. Mark scan as Private if handling sensitive inquiries.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 27800,
    tags: ["domain", "url-analysis", "sandbox", "screenshots", "phishing"]
  },
  {
    name: "Shodan Domain Search",
    categorySlug: "domain",
    url: "https://www.shodan.io",
    description: "Search engine for Internet-connected devices, indexed banners, web servers, open ports, and vulnerabilities.",
    usageContext: "Discover open ports, webcams, industrial control systems, and unauthenticated databases belonging to a domain or IP block.",
    inputOutput: "Input: hostname:target.com or net:CIDR | Output: Exposed ports, software versions, CVE vulnerabilities",
    opsecNotes: "Completely passive scanning; queries Shodan's pre-collected internet crawler dataset.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 520,
    views: 32000,
    tags: ["domain", "shodan", "iot", "open-ports", "banners"]
  },
  {
    name: "Censys Search",
    categorySlug: "domain",
    url: "https://search.censys.io",
    description: "Authoritative internet scanner providing deep visibility into every public IPv4/IPv6 host and TLS certificate.",
    usageContext: "Unmasking origins of websites hiding behind Cloudflare by matching unique TLS certificates to origin IP addresses.",
    inputOutput: "Input: Certificate SHA256 or domain | Output: Origin IP addresses, open services, cipher suites",
    opsecNotes: "Unmasking Cloudflare origin IPs is a fundamental investigative workflow.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 380,
    views: 22400,
    tags: ["domain", "censys", "ssl", "unmask-origin", "cloudflare"]
  },
  {
    name: "GrayhatWarfare",
    categorySlug: "domain",
    url: "https://grayhatwarfare.com",
    description: "Search engine indexing public and misconfigured Amazon AWS S3 Buckets, Azure Blobs, and DigitalOcean Spaces.",
    usageContext: "Finding leaked internal documents, database backups, source code, and customer records left in open cloud buckets.",
    inputOutput: "Input: Company name or domain keyword | Output: Direct links to exposed files and bucket names",
    opsecNotes: "Downloading confidential files may have legal implications. Verify authorization before downloading content.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.6,
    ratingCount: 240,
    views: 15300,
    tags: ["domain", "s3-buckets", "cloud-storage", "data-leaks"]
  },
  {
    name: "Robtex",
    categorySlug: "domain",
    url: "https://www.robtex.com",
    description: "IP and domain information service visualizing reverse DNS, routing loops, autonomous systems, and shared mail exchangers.",
    usageContext: "Quick visual inspection of shared hosting networks and nameserver infrastructure.",
    inputOutput: "Input: Domain / IP | Output: Visual relationship graph, historical shared IP counts",
    opsecNotes: "Passive directory query.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 160,
    views: 9800,
    tags: ["domain", "robtex", "visual-graphs", "nameservers"]
  },
  {
    name: "Netcraft Site Report",
    categorySlug: "domain",
    url: "https://sitereport.netcraft.com",
    description: "Detailed analysis of site uptime, historical hosting providers, nameservers, SSL certificate chain, and risk rating.",
    usageContext: "Assessing website history since the 1990s and identifying hosting migration trails.",
    inputOutput: "Input: Domain URL | Output: Netcraft risk score, historical web server OS, geolocation history",
    opsecNotes: "Safe passive lookup.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 180,
    views: 11500,
    tags: ["domain", "netcraft", "site-history", "hosting-trail"]
  },

  // --- 4. IP ADDRESS & GEOLOCATION ---
  {
    name: "IPinfo.io",
    categorySlug: "ip-address",
    url: "https://ipinfo.io",
    description: "Comprehensive IP address data API providing geolocation, ASN information, hosting company, and VPN/proxy detection.",
    usageContext: "Pinpoint physical server locations, identify hosting providers (AWS, Hetzner, DigitalOcean), and detect anonymity proxies.",
    inputOutput: "Input: IPv4 / IPv6 address | Output: City, Region, Country, Postal, Lat/Long, ASN, Company name, Privacy flag",
    opsecNotes: "Free tier provides 50k requests/month. Queries do not alert the target IP address.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 390,
    views: 24500,
    tags: ["ip-address", "geolocation", "asn", "vpn-detection", "essential"]
  },
  {
    name: "AbuseIPDB",
    categorySlug: "ip-address",
    url: "https://www.abuseipdb.com",
    description: "Centralized repository where webmasters and security analysts report malicious IPs engaging in hacking, spamming, and brute force.",
    usageContext: "Checking if an IP address has an active history of malicious behavior, SSH brute-forcing, or DDoS participation.",
    inputOutput: "Input: IP address | Output: Abuse confidence score, total reports, reporter comments, port attack history",
    opsecNotes: "Community reports provide real-time indicators of compromised bots or malicious VPN exit nodes.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 430,
    views: 27100,
    tags: ["ip-address", "threat-intel", "abuse-reports", "brute-force"]
  },
  {
    name: "MaxMind GeoIP2",
    categorySlug: "ip-address",
    url: "https://www.maxmind.com/en/geoip-demo",
    description: "The global gold standard in IP geolocation and anonymous proxy database intelligence.",
    usageContext: "Obtaining highest-accuracy geographic coordinates, ISP names, and connection types for forensic IP logs.",
    inputOutput: "Input: IP address | Output: City, coordinates, accuracy radius, ISP, connection speed",
    opsecNotes: "IP geolocation indicates ISP node location, not the exact physical residence of an individual.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 19800,
    tags: ["ip-address", "maxmind", "accuracy", "isp"]
  },
  {
    name: "GreyNoise Visualizer",
    categorySlug: "ip-address",
    url: "https://viz.greynoise.io",
    description: "Analyzes 'Internet Background Noise' to determine if an IP is scanning everyone (benign/malicious mass crawler) or targeting you specifically.",
    usageContext: "Filtering out common internet noise (Shodan, Qualys, Mirai scans) to isolate targeted adversaries.",
    inputOutput: "Input: IP address | Output: Classification (Benign, Malicious, Unknown), actor tags, destination ports scanned",
    opsecNotes: "Essential for triage in SOC and digital forensics investigations.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 265,
    views: 16900,
    tags: ["ip-address", "greynoise", "internet-noise", "triage"]
  },
  {
    name: "Hurricane Electric BGP Toolkit",
    categorySlug: "ip-address",
    url: "https://bgp.he.net",
    description: "The definitive routing and autonomous system lookup service displaying BGP peers, prefixes, IXPs, and WHOIS contacts.",
    usageContext: "Tracing routing paths, AS peers, IP prefix allocations, and corporate internet service provider contracts.",
    inputOutput: "Input: AS Number, IP, or prefix | Output: Interactive BGP graph, route announcements, upstream peers",
    opsecNotes: "Completely passive global route table queries.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 380,
    views: 22900,
    tags: ["ip-address", "bgp", "asn", "routing", "infrastructure"]
  },
  {
    name: "IPQualityScore (IPQS)",
    categorySlug: "ip-address",
    url: "https://www.ipqualityscore.com/ip-lookup",
    description: "Enterprise fraud prevention tool detecting residential proxies, Tor exit nodes, VPN tunnels, and botnet IPs.",
    usageContext: "Verifying whether an IP address is a genuine residential connection or an anonymized commercial proxy.",
    inputOutput: "Input: IP address | Output: Fraud score (0-100), proxy/VPN flag, bot status, ISP risk level",
    opsecNotes: "Offers free daily lookups; comprehensive residential proxy detection.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.6,
    ratingCount: 190,
    views: 13400,
    tags: ["ip-address", "fraud-detection", "residential-proxy", "vpn"]
  },
  {
    name: "Spur.us",
    categorySlug: "ip-address",
    url: "https://spur.us",
    description: "Premier intelligence feed on commercial VPN services, residential proxy networks, and bulletproof hosting infrastructure.",
    usageContext: "Attributing anonymous cyber attack traffic back to specific commercial proxy vendors (e.g. Luminati, Oxylabs).",
    inputOutput: "Input: IP address | Output: VPN service name, protocol used, client device types, operational footprint",
    opsecNotes: "Elite data used by major law enforcement and threat intelligence units.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 215,
    views: 14700,
    tags: ["ip-address", "spur", "proxy-infrastructure", "vpn-attribution"]
  },
  {
    name: "Tor Node Metrics",
    categorySlug: "ip-address",
    url: "https://metrics.torproject.org/rs.html",
    description: "Official Relay Search for the Tor network, listing all active and historical guard, middle, and exit relays.",
    usageContext: "Proving whether a server connection or web login originated from a verified Tor exit relay.",
    inputOutput: "Input: IP or relay fingerprint | Output: Tor flags (Exit, Guard, Fast, Stable), bandwidth, contact info",
    opsecNotes: "Official Tor Project dataset.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 340,
    views: 20100,
    tags: ["ip-address", "tor", "exit-relays", "anonymity"]
  },

  // --- 5. SOCIAL MEDIA INTELLIGENCE ---
  {
    name: "Bellingcat Open Source Toolkit",
    categorySlug: "social-media",
    url: "https://www.bellingcat.com/resources/how-tos/",
    description: "Curated repository of investigative methodologies, custom scripts, and verified workflows from Bellingcat journalists.",
    usageContext: "Guides for geo-locating conflict footage, tracking military equipment, and verifying social media claims.",
    inputOutput: "Input: Research problem | Output: Step-by-step verified OSINT methodologies, tool recommendations",
    opsecNotes: "Essential reading for ethical standards and rigorous investigative verification.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 620,
    views: 38000,
    tags: ["social-media", "bellingcat", "verification", "methodologies", "gold-standard"]
  },
  {
    name: "Twitonomy",
    categorySlug: "social-media",
    url: "https://www.twitonomy.com",
    description: "Deep Twitter/X analytics tool generating visual breakdowns of tweets, retweets, replies, mentions, and hashtag patterns.",
    usageContext: "Analyzing a target's posting schedule to deduce their primary timezone, most frequent interactors, and client software used.",
    inputOutput: "Input: Twitter/X handle | Output: Visual activity charts, tweet frequency by hour, top mentioned users",
    opsecNotes: "Requires Twitter account authentication to run queries.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.6,
    ratingCount: 240,
    views: 15800,
    tags: ["social-media", "twitter", "x", "analytics", "timezone"]
  },
  {
    name: "Social Bearing",
    categorySlug: "social-media",
    url: "https://www.socialbearing.com",
    description: "Free Twitter analytics tool tracking engagement, geolocation mentions, sentiment, influencers, and tweet timelines.",
    usageContext: "Mapping conversation sentiment around breaking news, protests, or brand crises in real time.",
    inputOutput: "Input: Handle or search query | Output: Sentiment breakdown, geolocated tweets map, engagement metrics",
    opsecNotes: "Requires Twitter/X API access.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 145,
    views: 9400,
    tags: ["social-media", "twitter", "sentiment", "geo-tweets"]
  },
  {
    name: "Snapchat Snap Map",
    categorySlug: "social-media",
    url: "https://map.snapchat.com",
    description: "Publicly accessible interactive world map displaying geotagged public snaps uploaded by Snapchat users globally.",
    usageContext: "Gathering ground-level eyewitness video footage of natural disasters, breaking news, protests, and police incidents.",
    inputOutput: "Input: Geographic coordinate / location | Output: Real-time public video snaps filmed at that location",
    opsecNotes: "Snaps are ephemeral (expire in 24 hours). Save videos immediately using screen recorders if capturing evidence.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 480,
    views: 31200,
    tags: ["social-media", "snapchat", "live-footage", "eyewitness", "geolocation"]
  },
  {
    name: "Reddit Search (Pushshift Archives)",
    categorySlug: "social-media",
    url: "https://redditsearch.io",
    description: "Search historical Reddit submissions, deleted comments, and subreddit posts by specific user and date range.",
    usageContext: "Investigating a subject's deleted Reddit posts, historical advice-seeking comments, and early hobby interests.",
    inputOutput: "Input: Author username / Subreddit | Output: Historical submissions and comments including deleted text",
    opsecNotes: "Indexes public historical dumps; captures comments before user deletion.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 19700,
    tags: ["social-media", "reddit", "deleted-comments", "pushshift"]
  },
  {
    name: "Telegram Web & Search",
    categorySlug: "social-media",
    url: "https://tgstat.com",
    description: "Comprehensive analytics catalog for Telegram channels, public groups, statistics, and forward tracking.",
    usageContext: "Tracing malware dissemination channels, propaganda propagation, and identifying source channels of forwarded leaks.",
    inputOutput: "Input: Channel handle or keyword | Output: Subscriber growth, forward tree, audience overlap",
    opsecNotes: "Telegram channels are primary venues for contemporary cybercrime, hacktivism, and war journalism.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 290,
    views: 18200,
    tags: ["social-media", "telegram", "channel-analytics", "disinformation"]
  },
  {
    name: "LinkedIn X-Ray Recruiter",
    categorySlug: "social-media",
    url: "https://recruitin.net",
    description: "Google dork generator optimized for searching public LinkedIn profiles by country, job title, company, and education.",
    usageContext: "Uncovering employee rosters, organizational charts, and executive profiles without triggering LinkedIn's 'Who Viewed Your Profile' notification.",
    inputOutput: "Input: Job title, company, country | Output: Pre-formatted Google X-Ray search query",
    opsecNotes: "Protects OPSEC because target never sees your LinkedIn account in their visitor logs.",
    toolFlags: "D",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 340,
    views: 22000,
    tags: ["social-media", "linkedin", "google-dork", "x-ray", "opsec-safe"]
  },
  {
    name: "Foller.me",
    categorySlug: "social-media",
    url: "https://foller.me",
    description: "Twitter profile analytics application providing tags, mentions, active hours, and linguistic analysis.",
    usageContext: "Rapid profiling of a Twitter user's network connections and habits in a clean card layout.",
    inputOutput: "Input: @username | Output: Visual word cloud, emoji usage, join date, followers ratio",
    opsecNotes: "Passive queries to Twitter public API.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.3,
    ratingCount: 120,
    views: 7800,
    tags: ["social-media", "twitter", "wordcloud", "profiling"]
  },

  // --- 6. GEOLOCATION & SATELLITE IMAGERY ---
  {
    name: "Sentinel Hub EO Browser",
    categorySlug: "geolocation",
    url: "https://apps.sentinel-hub.com/eo-browser/",
    description: "Free access to high-revisit satellite imagery archives (Sentinel-2, Landsat, Envisat) with multispectral bands (NDVI, false-color).",
    usageContext: "Tracking wildfire progression, military base construction, flooding, agricultural changes, and airfield activity globally.",
    inputOutput: "Input: Target coordinates & date | Output: Multi-spectral satellite images, infrared analysis, time-lapse video",
    opsecNotes: "Revisit rate is typically every 5 days; optical resolution is 10m/pixel.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 510,
    views: 31500,
    tags: ["geolocation", "satellite", "sentinel", "multispectral", "imagery"]
  },
  {
    name: "SunCalc",
    categorySlug: "geolocation",
    url: "https://www.suncalc.org",
    description: "Astronomical calculation tool showing sun movement, sunlight phases, shadow lengths, and sun angles for any given location and date/time.",
    usageContext: "Chronolocation: calculating the exact time of day a photo or video was taken by measuring object shadow lengths.",
    inputOutput: "Input: Location pin + Date | Output: Sun azimuth, elevation angle, shadow length multiplier",
    opsecNotes: "Indispensable forensic tool for confirming or debunking timestamp claims in photo/video evidence.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 590,
    views: 36200,
    tags: ["geolocation", "suncalc", "chronolocation", "shadows", "verification"]
  },
  {
    name: "Flightradar24",
    categorySlug: "geolocation",
    url: "https://www.flightradar24.com",
    description: "Real-time worldwide flight tracking service receiving live ADS-B data from thousands of terrestrial receivers.",
    usageContext: "Tracking private jets of oligarchs, government VIP transport, military recon flights, and medical evacuations.",
    inputOutput: "Input: Flight number, tail callsign, or map | Output: Live altitude, speed, route history, aircraft registration",
    opsecNotes: "Some military aircraft are filtered on commercial feeds; use ADSBexchange for unfiltered tracking.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 650,
    views: 42000,
    tags: ["geolocation", "flight-tracking", "aviation", "ads-b", "real-time"]
  },
  {
    name: "MarineTraffic",
    categorySlug: "geolocation",
    url: "https://www.marinetraffic.com",
    description: "Global ship tracking intelligence providing real-time positions of vessels and yachts using coastal AIS receiver stations.",
    usageContext: "Tracking oil tankers, sanctions evasion, illegal fishing, cargo transport, and billionaire superyachts.",
    inputOutput: "Input: Vessel name, IMO number, or MMSI | Output: Current coordinate, destination port, draught, photos",
    opsecNotes: "Vessels engaged in illicit trade may disable AIS transponders ('going dark'); cross-reference with SAR satellite imagery.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 410,
    views: 26000,
    tags: ["geolocation", "maritime", "ships", "ais", "vessels"]
  },
  {
    name: "Google Earth Pro (Desktop)",
    categorySlug: "geolocation",
    url: "https://www.google.com/earth/about/versions/",
    description: "Desktop geospatial software with high-resolution historical satellite imagery slider dating back decades and 3D terrain modeling.",
    usageContext: "Comparing past vs present construction, analyzing topographical sightlines, and measuring distances precisely.",
    inputOutput: "Input: Coordinate coordinates / KML | Output: Historical imagery timeline, 3D building perspective, elevation profiles",
    opsecNotes: "The historical imagery slider is the most potent free verification asset available to investigators.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 710,
    views: 45000,
    tags: ["geolocation", "google-earth", "historical-imagery", "3d", "terrain"]
  },
  {
    name: "Liveuamap",
    categorySlug: "geolocation",
    url: "https://liveuamap.com",
    description: "Geolocated open-source news and incident mapping platform covering conflicts, protests, refugee movements, and natural disasters.",
    usageContext: "Real-time situational awareness on ground-level territorial changes, airstrikes, and civil unrest worldwide.",
    inputOutput: "Input: Geographic theater | Output: Map pins with linked social media videos, news sources, and frontline changes",
    opsecNotes: "Aggregates social reports; always independently verify high-consequence claims.",
    toolFlags: "T",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 380,
    views: 24500,
    tags: ["geolocation", "conflict-map", "liveuamap", "incidents", "breaking-news"]
  },
  {
    name: "DualMaps",
    categorySlug: "geolocation",
    url: "https://www.dualmaps.com",
    description: "Combines Google Maps, Google Street View, and Bing Maps aerial bird's-eye photography into a synchronized split view.",
    usageContext: "Simultaneously comparing oblique aerial angles with ground-level panoramic street views for rapid building identification.",
    inputOutput: "Input: Address or coordinates | Output: Synchronized 3-way split screen",
    opsecNotes: "Speeds up geolocation verification by eliminating tab switching.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 190,
    views: 12800,
    tags: ["geolocation", "split-view", "aerial", "streetview"]
  },
  {
    name: "Windy.com",
    categorySlug: "geolocation",
    url: "https://www.windy.com",
    description: "Interactive weather radar, satellite animation, wind streamlines, wave forecasts, and live outdoor webcams across the globe.",
    usageContext: "Verifying weather conditions (cloud cover, rain, wind direction) claimed in videos or satellite imagery at a specific hour.",
    inputOutput: "Input: Location + date | Output: ECMWF/GFS weather model replay, active outdoor camera streams",
    opsecNotes: "Weather verification is crucial for corroborating alibis and debunking fabricated footage.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 29000,
    tags: ["geolocation", "weather", "radar", "webcams", "wind"]
  },
  {
    name: "PeakFinder",
    categorySlug: "geolocation",
    url: "https://www.peakfinder.org",
    description: "Renders 360-degree panoramic mountain horizon profiles from any geographic coordinate on Earth.",
    usageContext: "Matching distant mountain skylines visible in background photos/videos to confirm exact camera position.",
    inputOutput: "Input: Latitude/Longitude | Output: 360-degree mountain silhouette drawing with peak names and elevations",
    opsecNotes: "Phenomenal tool for geolocating rural, mountainous, or conflict-zone footage.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 220,
    views: 14100,
    tags: ["geolocation", "mountains", "horizon", "terrain-matching"]
  },

  // --- 7. SEARCH ENGINES & GOOGLE DORKS ---
  {
    name: "Google Hacking Database (GHDB)",
    categorySlug: "search-dorks",
    url: "https://www.exploit-db.com/google-hacking-database",
    description: "Comprehensive crowd-sourced index of Google search queries ('dorks') designed to uncover sensitive files, passwords, vulnerable servers, and portals.",
    usageContext: "Discovering exposed admin panels, unprotected webcam streams, leaked config files, and indexed confidential spreadsheets.",
    inputOutput: "Input: Category filter (e.g. sensitive directories, web servers) | Output: Verified Google dork strings with search launch links",
    opsecNotes: "Executing dorks directly against a target domain may trigger alerts in Google Captcha or target WAF logs.",
    toolFlags: "D",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 570,
    views: 35000,
    tags: ["search-dorks", "ghdb", "exploit-db", "google-dorks", "essential"]
  },
  {
    name: "Intelligence X Search",
    categorySlug: "search-dorks",
    url: "https://intelx.io",
    description: "Search engine and data archive indexing the darknet, leak forums, paste sites, historical WHOIS, and public document drops.",
    usageContext: "Locating historical pastes, leaked database records, and obscure dark web forum discussions for arbitrary search terms.",
    inputOutput: "Input: Email, domain, IP, CIDR, Bitcoin address | Output: Archived pastes, full text documents, dark web snapshots",
    opsecNotes: "Results include unredacted raw breach material; handle findings responsibly.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 490,
    views: 31000,
    tags: ["search-dorks", "intelx", "darknet", "paste-search"]
  },
  {
    name: "FOFA Pro Search",
    categorySlug: "search-dorks",
    url: "https://en.fofa.info",
    description: "Cyberspace search engine indexing internet infrastructure, SSL certificates, title tags, and open ports with extensive Asian asset coverage.",
    usageContext: "Discovering internet assets and mapping infrastructure with specialized queries like body='admin' && country='US'.",
    inputOutput: "Input: Custom FOFA syntax | Output: IP list, open ports, web banners, certificate details",
    opsecNotes: "Massive complementary dataset to Shodan and Censys.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 280,
    views: 17800,
    tags: ["search-dorks", "fofa", "cyberspace", "iot", "infrastructure"]
  },
  {
    name: "PublicWWW Source Code Search",
    categorySlug: "search-dorks",
    url: "https://publicwww.com",
    description: "Source code search engine indexing the HTML, JavaScript, CSS, and backend code signatures of hundreds of millions of websites.",
    usageContext: "Searching for specific affiliate tracking IDs, private API keys accidentally leaked in frontend code, or unique CMS widgets.",
    inputOutput: "Input: Code snippet, snippet regex, or ID tag | Output: All websites containing that exact code block",
    opsecNotes: "Unrivaled for discovering connected networks of affiliate sites created by the same developer.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.8,
    ratingCount: 230,
    views: 15200,
    tags: ["search-dorks", "source-code", "html-search", "attribution"]
  },
  {
    name: "Carrot2 Clustering Engine",
    categorySlug: "search-dorks",
    url: "https://search.carrot2.org",
    description: "Search results clustering engine organizing queries into thematic topics, hierarchical categories, and visual foam trees.",
    usageContext: "Identifying unexpected topic clusters, sub-narratives, and associated entities when researching unfamiliar subjects.",
    inputOutput: "Input: Search query | Output: Interactive visual topic clusters and foam tree visualization",
    opsecNotes: "Synthesizes open web results into thematic clusters automatically.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 160,
    views: 10200,
    tags: ["search-dorks", "clustering", "visualization", "topics"]
  },
  {
    name: "Million Short",
    categorySlug: "search-dorks",
    url: "https://millionshort.com",
    description: "Alternative search engine allowing users to remove the top 100, 10,000, or 1,000,000 most popular sites from results.",
    usageContext: "Bypassing SEO content farms, mainstream corporate blogs, and sponsored results to uncover hidden niche forums.",
    inputOutput: "Input: Query + filter selection | Output: Search results excluding mega-websites (Wikipedia, Amazon, Forbes)",
    opsecNotes: "Valuable for discovering primary sources on small, personal websites.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 210,
    views: 13900,
    tags: ["search-dorks", "unfiltered", "niche-forums", "bypass-seo"]
  },
  {
    name: "DuckDuckGo !Bangs",
    categorySlug: "search-dorks",
    url: "https://duckduckgo.com/bangs",
    description: "Shortcuts that quickly search over 13,000 websites directly from your search bar (e.g. !gh for GitHub, !w for Wikipedia).",
    usageContext: "Rapid targeted jumping between OSINT repos, code repositories, and regional search databases.",
    inputOutput: "Input: !bang + search terms | Output: Direct redirected search inside destination platform",
    opsecNotes: "Client queries route via DuckDuckGo without tracking cookies.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 250,
    views: 16500,
    tags: ["search-dorks", "duckduckgo", "bangs", "shortcuts"]
  },

  // --- 8. PUBLIC RECORDS & CORPORATE DATA ---
  {
    name: "OpenCorporates",
    categorySlug: "public-records",
    url: "https://opencorporates.com",
    description: "The largest open database of companies in the world, aggregating over 200 million company records across 140+ jurisdictions.",
    usageContext: "Investigating corporate ownership, subsidiary networks, director histories, and identifying shell companies.",
    inputOutput: "Input: Company name or Officer/Director name | Output: Incorporation date, registered address, officers, filings",
    opsecNotes: "Public records aggregator; safe passive lookup.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 520,
    views: 33400,
    tags: ["public-records", "corporate", "opencorporates", "company-filings", "directors"]
  },
  {
    name: "ICIJ Offshore Leaks Database",
    categorySlug: "public-records",
    url: "https://offshoreleaks.icij.org",
    description: "Searchable database of over 810,000 offshore entities from the Pandora Papers, Panama Papers, Paradise Papers, and FinCEN Files.",
    usageContext: "Exposing beneficial owners, secret offshore bank accounts, and tax-haven entities linked to politicians and business magnates.",
    inputOutput: "Input: Name, Country, or Entity | Output: Interactive network graph showing intermediary agents, trusts, and ultimate owners",
    opsecNotes: "Historic leak documents curated by the International Consortium of Investigative Journalists.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 640,
    views: 39800,
    tags: ["public-records", "panama-papers", "offshore", "icij", "corruption"]
  },
  {
    name: "SEC EDGAR Filings",
    categorySlug: "public-records",
    url: "https://www.sec.gov/edgar/searchedgar/companysearch",
    description: "Official United States Securities and Exchange Commission database of corporate financial disclosures (10-K, 10-Q, 8-K, S-1).",
    usageContext: "Reading audited financial statements, executive compensation, material litigations, and major stock sales by corporate insiders.",
    inputOutput: "Input: Public company ticker or name | Output: Official regulatory filings, balance sheets, executive agreements",
    opsecNotes: "Government repository; all public companies traded in the US are legally required to submit filings.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 370,
    views: 24000,
    tags: ["public-records", "sec", "edgar", "corporate-finance", "insiders"]
  },
  {
    name: "CourtListener & RECAP Archive",
    categorySlug: "public-records",
    url: "https://www.courtlistener.com",
    description: "Free legal research website providing millions of legal opinions, PACER federal court dockets, and audio oral arguments.",
    usageContext: "Discovering active lawsuits, criminal indictments, grand jury dockets, and settlement agreements involving people or companies.",
    inputOutput: "Input: Person name, company name, or case docket | Output: Legal briefs, court transcripts, PDF filings",
    opsecNotes: "Community-driven open access alternative to paid PACER searches.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 410,
    views: 26800,
    tags: ["public-records", "court-records", "pacer", "lawsuits", "legal"]
  },
  {
    name: "UK Companies House Service",
    categorySlug: "public-records",
    url: "https://find-and-update.company-information.service.gov.uk",
    description: "Official UK government company registry offering free downloads of company accounts, officer lists, and Persons with Significant Control (PSC).",
    usageContext: "Identifying British company owners, residential address filings of directors, and financial solvency accounts.",
    inputOutput: "Input: UK Company name or Director name | Output: PSC registers, annual accounts, change of directors history",
    opsecNotes: "One of the most transparent national corporate registries globally.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 29500,
    tags: ["public-records", "uk-companies", "companies-house", "psc-register"]
  },
  {
    name: "OpenSanctions",
    categorySlug: "public-records",
    url: "https://www.opensanctions.org",
    description: "International open database of persons and companies of political, criminal, or economic interest: sanctions, PEPs, and debarred entities.",
    usageContext: "Compliance and background checks to verify if an individual or firm is under international sanctions (OFAC, EU, UN).",
    inputOutput: "Input: Entity name | Output: Sanction lists matches, aliases, dates of birth, related entities",
    opsecNotes: "Aggregates data from hundreds of worldwide regulatory watchdogs.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 20200,
    tags: ["public-records", "sanctions", "ofac", "pep", "compliance"]
  },
  {
    name: "LittleSis Power Mapping",
    categorySlug: "public-records",
    url: "https://littlesis.org",
    description: "Free database detailing connections between powerful people and organizations in business and government.",
    usageContext: "Investigating conflicts of interest, lobbying relationships, political donors, and board memberships.",
    inputOutput: "Input: Politician or corporate executive | Output: Interactive relationship diagram, campaign contributions",
    opsecNotes: "Community-maintained research tool.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 190,
    views: 12400,
    tags: ["public-records", "lobbying", "power-mapping", "conflicts-of-interest"]
  },
  {
    name: "Panjiva Global Trade",
    categorySlug: "public-records",
    url: "https://panjiva.com",
    description: "Commercial intelligence platform tracking global trade flows, maritime bills of lading, customs records, and supply chains.",
    usageContext: "Tracing international shipments, suppliers, buyers, cargo contents, and customs export declarations.",
    inputOutput: "Input: Importer/Exporter company | Output: Bill of lading records, ports of origin, shipping containers",
    opsecNotes: "Commercial subscription required for full dataset; free summary samples available.",
    toolFlags: "R",
    isFree: 0,
    ratingAvg: 4.7,
    ratingCount: 220,
    views: 14600,
    tags: ["public-records", "customs", "shipping", "supply-chain", "trade"]
  },

  // --- 9. DOCUMENTS & METADATA EXTRACTION ---
  {
    name: "ExifTool by Phil Harvey",
    categorySlug: "documents-metadata",
    url: "https://exiftool.org",
    description: "The gold standard command-line library for reading, writing, and editing meta information in a vast variety of file formats.",
    usageContext: "Extracting camera serial numbers, lens models, GPS coordinates, author names, creation software, and embedded thumbnails.",
    inputOutput: "Input: Image, PDF, Office document, video | Output: Complete dump of all EXIF, XMP, IPTC, and maker note tags",
    opsecNotes: "Always inspect EXIF metadata locally before publishing research files to avoid leaking your own workstation details.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 780,
    views: 49000,
    tags: ["documents-metadata", "exiftool", "exif", "gps-metadata", "cli", "gold-standard"]
  },
  {
    name: "CyberChef",
    categorySlug: "documents-metadata",
    url: "https://gchq.github.io/CyberChef/",
    description: "The 'Cyber Swiss Army Knife' by GCHQ: a web app for encryption, encoding, compression, data parsing, and format transformation.",
    usageContext: "Decoding Base64 strings, parsing JSON, extracting URLs from raw dumps, hashing data, and carving payloads.",
    inputOutput: "Input: Raw input bytes or strings | Output: Converted, decoded, or carved output through modular recipe chains",
    opsecNotes: "Runs 100% locally in the browser memory. No data is sent over the network to remote servers.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 890,
    views: 58000,
    tags: ["documents-metadata", "cyberchef", "gchq", "decoding", "hashing", "essential"]
  },
  {
    name: "Metadata2Go",
    categorySlug: "documents-metadata",
    url: "https://www.metadata2go.com",
    description: "Online EXIF and document metadata viewer allowing quick drag-and-drop inspection of files directly in browser.",
    usageContext: "Fast metadata extraction without needing to install command-line tools like ExifTool on your host machine.",
    inputOutput: "Input: Uploaded file | Output: Structured table of detected metadata, camera info, and GPS coordinates",
    opsecNotes: "Uploads file to third-party server. Do NOT upload classified, sensitive, or confidential investigative evidence.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.4,
    ratingCount: 160,
    views: 11000,
    tags: ["documents-metadata", "web-viewer", "drag-and-drop", "quick-check"]
  },
  {
    name: "PDF-Parser by Didier Stevens",
    categorySlug: "documents-metadata",
    url: "https://blog.didierstevens.com/programs/pdf-tools/",
    description: "Python CLI utility to parse PDF documents, identifying embedded JavaScript, stream objects, suspicious actions, and revision history.",
    usageContext: "Forensic examination of weaponized PDFs, malicious document attachments, and extracting hidden revision streams.",
    inputOutput: "Input: PDF file | Output: Object dump, embedded scripts, indirect references, stream contents",
    opsecNotes: "Safely analyzes PDFs without triggering active Adobe Reader exploit chains.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 270,
    views: 17400,
    tags: ["documents-metadata", "pdf", "didier-stevens", "malware-analysis", "forensics"]
  },
  {
    name: "FOCA (Fingerprinting Organizations with Collected Archives)",
    categorySlug: "documents-metadata",
    url: "https://github.com/ElevenPaths/FOCA",
    description: "Automates downloading of public documents (.pdf, .doc, .xls) from a target website to extract users, printers, software versions, and paths.",
    usageContext: "Extracting employee usernames, network folder paths (C:\\Users\\john\\...), and internal server names from public PDFs.",
    inputOutput: "Input: Target domain name | Output: Organizational network map, employee names, internal printer/folder shares",
    opsecNotes: "Uncovers profound internal infrastructure intelligence leaked inadvertently inside public brochures and reports.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 310,
    views: 19800,
    tags: ["documents-metadata", "foca", "document-scraping", "internal-usernames"]
  },
  {
    name: "Jeffrey's Image Metadata Viewer",
    categorySlug: "documents-metadata",
    url: "http://exif.regex.info/exif.cgi",
    description: "Extensive web-based image EXIF inspector powered by ExifTool with direct interactive Google Maps GPS integration.",
    usageContext: "Checking image files directly via URL to inspect geolocation without downloading the file to your disk.",
    inputOutput: "Input: Image URL or file upload | Output: Complete EXIF dump, lens profiles, embedded Google Map pin",
    opsecNotes: "Veteran utility online since 2006; reliable and accurate.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 180,
    views: 12500,
    tags: ["documents-metadata", "exif", "gps-mapping", "web-viewer"]
  },

  // --- 10. IMAGE & VIDEO FORENSICS ---
  {
    name: "Google Lens",
    categorySlug: "image-video",
    url: "https://lens.google.com",
    description: "Advanced visual search engine leveraging computer vision to identify landmarks, products, buildings, text, and artwork.",
    usageContext: "Quickly identifying the exact location or building facade shown in an untagged photograph.",
    inputOutput: "Input: Image upload or crop box | Output: Visually similar web images, recognized landmark name, OCR text",
    opsecNotes: "Submitting images to Google stores them in search telemetry; crop out identifying faces or sensitive details first.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 680,
    views: 43000,
    tags: ["image-video", "google-lens", "visual-search", "landmarks", "essential"]
  },
  {
    name: "Yandex Visual Search",
    categorySlug: "image-video",
    url: "https://yandex.com/images/",
    description: "Renowned as one of the most effective reverse image search algorithms for finding identical human faces and foreign landmarks.",
    usageContext: "Tracking down original source profiles for portrait photos, identifying unknown people, and locating Russian/Eastern European imagery.",
    inputOutput: "Input: Photograph / Portrait | Output: Matching web pages, identical or cropped copies of the person's face",
    opsecNotes: "Superior facial matching capabilities compared to standard western search engines.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 590,
    views: 38200,
    tags: ["image-video", "yandex", "facial-matching", "reverse-image", "gold-standard"]
  },
  {
    name: "TinEye Reverse Image Search",
    categorySlug: "image-video",
    url: "https://tineye.com",
    description: "Reverse image search engine specialized in finding exact duplicates, image modifications, higher-resolution versions, and first appearance dates.",
    usageContext: "Finding the earliest known date an image appeared on the internet to determine if a viral photo is recycled old news.",
    inputOutput: "Input: Image file or URL | Output: Chronological list of indexed occurrences, modified versions, crops",
    opsecNotes: "Sort by 'Oldest' to pinpoint the original publisher of a viral image.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 420,
    views: 28500,
    tags: ["image-video", "tineye", "chronology", "oldest-appearance", "crops"]
  },
  {
    name: "FotoForensics",
    categorySlug: "image-video",
    url: "https://fotoforensics.com",
    description: "Forensic image analysis tool providing Error Level Analysis (ELA), hidden metadata inspection, and JPEG quality estimations.",
    usageContext: "Detecting digital manipulation: identifying inserted objects, photoshopped text, cloned pixels, and compression differences.",
    inputOutput: "Input: JPEG/PNG image | Output: ELA rainbow visualization highlighting regions with mismatched compression levels",
    opsecNotes: "ELA highlights compression disparities; interpret results carefully to avoid false positives on high-contrast edges.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 390,
    views: 26000,
    tags: ["image-video", "ela", "manipulation-detection", "photoshop-check", "forensics"]
  },
  {
    name: "Forensically",
    categorySlug: "image-video",
    url: "https://29a.ch/forensically/",
    description: "Free in-browser digital image forensics suite with Magnifier, Clone Detection, Error Level Analysis, Noise Analysis, and GPS extraction.",
    usageContext: "Comprehensive forensic examination of digital photographs completely inside your local browser sandbox.",
    inputOutput: "Input: Image file | Output: Interactive ELA, clone brush detection matrices, level adjustments",
    opsecNotes: "Client-side processing guarantees your evidence is never uploaded to remote cloud servers.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 470,
    views: 31000,
    tags: ["image-video", "forensically", "client-side", "clone-detection", "ela"]
  },
  {
    name: "InVID & WeVerify Verification Plugin",
    categorySlug: "image-video",
    url: "https://www.invid-project.eu/tools-and-services/invid-verification-plugin/",
    description: "Browser extension designed for fact-checkers to verify video footage, perform video keyframe extraction, and reverse-search clips.",
    usageContext: "Debunking fake viral news videos by splitting videos into keyframe thumbnails and reverse-searching them across multiple engines.",
    inputOutput: "Input: YouTube, Facebook, Twitter, or local video | Output: Keyframes, reverse search results, Twitter advanced search queries",
    opsecNotes: "Standard utility mandated in investigative newsrooms worldwide.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 440,
    views: 29200,
    tags: ["image-video", "invid", "video-verification", "fact-checking", "keyframes"]
  },
  {
    name: "PimEyes Face Search",
    categorySlug: "image-video",
    url: "https://pimeyes.com",
    description: "Extremely potent AI-powered facial recognition search engine scanning the open web for matching human faces across platforms.",
    usageContext: "Locating all public appearances of a person's face across news articles, public company websites, blogs, and adult platforms.",
    inputOutput: "Input: Face photo | Output: Thumbnails of matching faces online, source website domains",
    opsecNotes: "Commercial subscription required to view full unredacted source URLs. Highly sensitive capability.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.7,
    ratingCount: 510,
    views: 34500,
    tags: ["image-video", "pimeyes", "facial-recognition", "biometrics", "powerful"]
  },

  // --- 11. THREAT INTELLIGENCE & MALWARE ---
  {
    name: "VirusTotal",
    categorySlug: "threat-intel",
    url: "https://www.virustotal.com",
    description: "Inspects suspicious files, domains, IPs, and URLs with over 70 antivirus scanners and URL/domain blocklists.",
    usageContext: "Determining whether a suspicious file or link is malicious, reviewing behavioral sandbox execution, and inspecting community comments.",
    inputOutput: "Input: File, URL, IP, domain, or file hash (MD5/SHA256) | Output: AV detection ratios, behavior graphs, relations",
    opsecNotes: "Files uploaded to VirusTotal are shared with the global cybersecurity community. NEVER upload confidential documents containing PII.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 890,
    views: 61000,
    tags: ["threat-intel", "virustotal", "antivirus", "malware", "hashes", "gold-standard"]
  },
  {
    name: "AlienVault OTX (Open Threat Exchange)",
    categorySlug: "threat-intel",
    url: "https://otx.alienvault.com",
    description: "Crowd-sourced computer-security platform providing access to threat data generated by over 200,000 security researchers worldwide.",
    usageContext: "Pivoting on indicators of compromise (IoCs) to discover associated threat actors (APTs), malware pulses, and adversary TTPs.",
    inputOutput: "Input: IoC (IP, domain, hash, CVE) | Output: Associated threat pulses, malware families, targeted industries",
    opsecNotes: "Free account gives access to complete community threat pulses.",
    toolFlags: "R",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 380,
    views: 24200,
    tags: ["threat-intel", "otx", "alienvault", "iocs", "apt-groups"]
  },
  {
    name: "ANY.RUN Interactive Sandbox",
    categorySlug: "threat-intel",
    url: "https://any.run",
    description: "Interactive online malware sandbox allowing analysts to watch malware execute in real-time inside an interactive virtual machine.",
    usageContext: "Safely opening malicious documents, following phishing redirects, and observing ransomware activity live.",
    inputOutput: "Input: Suspicious file or phishing link | Output: Live VM session, process tree, network traffic, downloaded payloads",
    opsecNotes: "Community tasks are public by default; do not upload sensitive proprietary documents.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.9,
    ratingCount: 460,
    views: 31000,
    tags: ["threat-intel", "sandbox", "any-run", "dynamic-analysis", "phishing"]
  },
  {
    name: "Hybrid Analysis",
    categorySlug: "threat-intel",
    url: "https://www.hybrid-analysis.com",
    description: "Free automated malware analysis service powered by Falcon Sandbox, analyzing suspicious files and detecting unknown threats.",
    usageContext: "In-depth static and dynamic behavioral analysis of executables, scripts, and Office macro malware.",
    inputOutput: "Input: File or URL | Output: Threat score, MITRE ATT&CK mapping, extracted network traffic (PCAP)",
    opsecNotes: "Provides downloadable PCAP files of malware network communications.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 350,
    views: 22800,
    tags: ["threat-intel", "hybrid-analysis", "mitre-attack", "sandbox", "pcap"]
  },
  {
    name: "MalwareBazaar by abuse.ch",
    categorySlug: "threat-intel",
    url: "https://bazaar.abuse.ch",
    description: "Community project collecting and sharing known malware samples to assist researchers, antivirus vendors, and CERT teams.",
    usageContext: "Downloading live malware binaries and ransomware samples for reverse-engineering and signature creation.",
    inputOutput: "Input: Tag, signature, or hash | Output: Downloadable password-protected malware ZIPs, C2 servers",
    opsecNotes: "Strictly for security professionals; handling live malware requires isolated offline lab environments.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 410,
    views: 26400,
    tags: ["threat-intel", "malware-samples", "abuse-ch", "reverse-engineering"]
  },
  {
    name: "URLhaus",
    categorySlug: "threat-intel",
    url: "https://urlhaus.abuse.ch",
    description: "Crowdsourced database dedicated to sharing malicious URLs being used for malware distribution.",
    usageContext: "Checking if a link is hosting active malware droppers or part of an ongoing phishing campaign.",
    inputOutput: "Input: URL or domain | Output: Status (online/offline), malware payload tags, reporter details",
    opsecNotes: "Provides daily downloadable blocklists for DNS firewalls.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 320,
    views: 19800,
    tags: ["threat-intel", "urlhaus", "malicious-urls", "c2", "payloads"]
  },
  {
    name: "Cisco Talos Intelligence",
    categorySlug: "threat-intel",
    url: "https://talosintelligence.com",
    description: "One of the largest commercial threat intelligence teams in the world, providing comprehensive IP, domain, and reputation lookups.",
    usageContext: "Investigating sender domain reputation, email volume spikes, and enterprise security blacklists.",
    inputOutput: "Input: IP, domain, or network owner | Output: Web reputation rating, email volume history, blacklists status",
    opsecNotes: "Authoritative enterprise threat reputation metric.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 290,
    views: 18500,
    tags: ["threat-intel", "cisco-talos", "reputation", "ip-blacklist"]
  },

  // --- 12. ARCHIVES & HISTORICAL CACHE ---
  {
    name: "Internet Archive Wayback Machine",
    categorySlug: "archives",
    url: "https://web.archive.org",
    description: "Digital archive of the World Wide Web containing over 800 billion web pages captured across time since 1996.",
    usageContext: "Recovering deleted web pages, past versions of corporate terms, historical staff pages, and altered political statements.",
    inputOutput: "Input: Website URL + Date calendar | Output: Functional historical snapshot of the target web page as it existed then",
    opsecNotes: "The ultimate weapon against online scrubbing and revisionist deletion.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 950,
    views: 65000,
    tags: ["archives", "wayback-machine", "historical-web", "deleted-pages", "gold-standard"]
  },
  {
    name: "Archive.today (Archive.is)",
    categorySlug: "archives",
    url: "https://archive.today",
    description: "Web archiving service taking instant, tamper-proof snapshots of web pages, preserving both text and visual screenshot copies.",
    usageContext: "Bypassing paywalls and preserving indisputable evidentiary snapshots of social media posts before they get deleted.",
    inputOutput: "Input: Live web URL | Output: Permanent archive URL with unalterable screenshot and clean DOM copy",
    opsecNotes: "Unlike Wayback Machine, Archive.today cannot be retroactively removed by webmasters via robots.txt.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 680,
    views: 44000,
    tags: ["archives", "archive-today", "evidence-preservation", "paywall-bypass", "tamper-proof"]
  },
  {
    name: "CachedView.com",
    categorySlug: "archives",
    url: "https://cachedview.com",
    description: "Multi-cache aggregator querying Google Web Cache, Wayback Machine, and Archive.today simultaneously.",
    usageContext: "Quickly checking every major historical cache provider in a single query when a target site is offline.",
    inputOutput: "Input: Target URL | Output: Direct links to cached mirrors across all providers",
    opsecNotes: "Saves time when looking for recently deleted blog posts or articles.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 210,
    views: 13500,
    tags: ["archives", "cache-aggregator", "google-cache", "wayback"]
  },
  {
    name: "GhostArchive",
    categorySlug: "archives",
    url: "https://ghostarchive.org",
    description: "Modern archive utility specialized in capturing YouTube video streams, Reddit comment trees, and Twitter timelines before deletion.",
    usageContext: "Preserving video evidence and social media comment threads with permanent download links.",
    inputOutput: "Input: Video link or social post | Output: Preserved MP4 video file and archived page",
    opsecNotes: "Essential for preserving eyewitness video uploads before platform takedowns.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 230,
    views: 15100,
    tags: ["archives", "ghostarchive", "video-archive", "social-preservation"]
  },
  {
    name: "Memory.lol",
    categorySlug: "archives",
    url: "https://memory.lol",
    description: "Historical database of Twitter / X handle changes, tracking previous usernames associated with an account ID.",
    usageContext: "Unmasking cybercriminals or fraudsters who change their Twitter handle to evade detection.",
    inputOutput: "Input: Current or previous Twitter username | Output: List of all previous handles used by that account with timestamps",
    opsecNotes: "Proves continuity of account ownership despite rebranding attempts.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 290,
    views: 19200,
    tags: ["archives", "twitter-history", "handle-changes", "rebranding-track"]
  },

  // --- 13. DARK WEB & TOR RESOURCES ---
  {
    name: "Ahmia.fi Tor Search Engine",
    categorySlug: "dark-web",
    url: "https://ahmia.fi",
    description: "Clearnet-accessible search engine indexing hidden services (.onion) on the Tor network with strict anti-abuse filtering.",
    usageContext: "Searching the Tor dark web directly from a standard web browser without needing Tor Browser installed.",
    inputOutput: "Input: Keywords or subject | Output: Indexed .onion addresses, page titles, and content previews",
    opsecNotes: "Filters out child abuse material; provides safe introductory access to darknet indexing.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 450,
    views: 29800,
    tags: ["dark-web", "ahmia", "onion-search", "tor", "clearnet-gateway"]
  },
  {
    name: "Tor Project Browser",
    categorySlug: "dark-web",
    url: "https://www.torproject.org",
    description: "The official browser routing traffic over the encrypted Tor volunteer relay network to provide privacy and access to .onion sites.",
    usageContext: "Browsing dark web hidden services safely, preserving investigator anonymity, and bypassing authoritarian censorship.",
    inputOutput: "Input: Onion URL or clearnet site | Output: Encrypted 3-hop circuit browsing session",
    opsecNotes: "Do not resize browser window or install browser extensions to prevent browser fingerprinting.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 820,
    views: 52000,
    tags: ["dark-web", "tor-browser", "onion", "anonymity", "essential"]
  },
  {
    name: "Dark.fail Onion Directory",
    categorySlug: "dark-web",
    url: "https://dark.fail",
    description: "Curated, PGP-verified directory tracking the real-time uptime status of major legitimate darknet markets, news sites, and forums.",
    usageContext: "Obtaining verified, non-phishing .onion mirror links for major darknet platforms.",
    inputOutput: "Input: Browse directory | Output: PGP-signed verified .onion addresses and live uptime status",
    opsecNotes: "Phishing onion mirrors are rampant; always verify mirrors against cryptographically signed lists like Dark.fail.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 490,
    views: 33000,
    tags: ["dark-web", "dark-fail", "onion-uptime", "pgp-verified", "anti-phishing"]
  },
  {
    name: "Ransomware.live",
    categorySlug: "dark-web",
    url: "https://www.ransomware.live",
    description: "Real-time monitoring platform tracking ransomware gang leak sites (LockBit, BlackCat, Akira, Play) and victim announcements.",
    usageContext: "Tracking cyber extortion events, discovering if a company has suffered a ransomware breach, and reading negotiation notes.",
    inputOutput: "Input: Company name or ransomware gang | Output: Victim list, published leak files, countdown timers, press releases",
    opsecNotes: "Invaluable for threat intelligence teams and cyber insurance adjusters.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 430,
    views: 28400,
    tags: ["dark-web", "ransomware", "leak-sites", "threat-intel", "extortion"]
  },
  {
    name: "Ransomlook.io",
    categorySlug: "dark-web",
    url: "https://www.ransomlook.io",
    description: "Open-source intelligence aggregator indexing ransomware group postings, Telegram leak channels, and data extortion announcements.",
    usageContext: "Monitoring newly claimed victims across 60+ active ransomware and data extortion threat groups.",
    inputOutput: "Input: Search company / domain | Output: Group attribution, date of claim, leaked proof archives",
    opsecNotes: "Aggregated in real-time from Tor hidden services.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 19600,
    tags: ["dark-web", "ransomlook", "extortion", "cybercrime", "victims"]
  },
  {
    name: "Tor66 Search",
    categorySlug: "dark-web",
    url: "http://tor66sewebda7xavpqdydspbtavlhghai73vd7igma3tfdvg7cesxdad.onion",
    description: "Fast hidden service search engine indexing tens of thousands of active .onion sites with recent crawl timestamps.",
    usageContext: "Deep search of darknet forums, hacker repositories, and leak pastes inside Tor Browser.",
    inputOutput: "Input: Target keyword | Output: Direct .onion links with crawl dates and title tags",
    opsecNotes: "Must be opened inside Tor Browser.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.5,
    ratingCount: 220,
    views: 14200,
    tags: ["dark-web", "tor66", "onion-crawler", "hidden-services"]
  },

  // --- 14. PEOPLE & DIRECTORY SEARCH ---
  {
    name: "FastPeopleSearch",
    categorySlug: "people-search",
    url: "https://www.fastpeoplesearch.com",
    description: "100% free US public records people finder providing full names, age, current address, past address history, relatives, and phone numbers.",
    usageContext: "Quickly locating residential address history, landline/mobile numbers, and identifying family members and associates.",
    inputOutput: "Input: Name + City/State or Phone | Output: Full legal name, estimated age, address history, relatives list, phone numbers",
    opsecNotes: "Only covers US residents; queries are fast and require no login or payment.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 520,
    views: 34000,
    tags: ["people-search", "us-records", "phone-lookup", "relatives", "free"]
  },
  {
    name: "TruePeopleSearch",
    categorySlug: "people-search",
    url: "https://www.truepeoplesearch.com",
    description: "Completely free directory to look up people in the United States by name, phone number, physical address, or email.",
    usageContext: "Reverse address search to find all current and prior tenants of a specific residential property.",
    inputOutput: "Input: Address, Phone, or Name | Output: Occupants list, phone carrier, previous residences, associates",
    opsecNotes: "Excellent for cross-referencing leads discovered in FastPeopleSearch.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 490,
    views: 31800,
    tags: ["people-search", "reverse-address", "phone", "occupants", "associates"]
  },
  {
    name: "FamilyTreeNow",
    categorySlug: "people-search",
    url: "https://www.familytreenow.com",
    description: "Genealogy and historical public records search engine with exceptionally detailed family relationship trees and living relatives lists.",
    usageContext: "Mapping out extended family trees, identifying maiden names, and establishing kinship connections.",
    inputOutput: "Input: Person name + state | Output: Detailed tree of immediate and extended relatives, historical addresses",
    opsecNotes: "Genealogy aggregators often reveal mother's maiden name, a frequent security question answer.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 380,
    views: 24600,
    tags: ["people-search", "genealogy", "family-tree", "kinship", "maiden-names"]
  },
  {
    name: "That's Them",
    categorySlug: "people-search",
    url: "https://thatsthem.com",
    description: "Free people search engine offering reverse email search, reverse phone lookup, VIN number lookup, and physical address queries.",
    usageContext: "Connecting an email address or vehicle VIN number directly to a named individual and residential address.",
    inputOutput: "Input: Name, Email, Phone, Address, or VIN | Output: Complete identity profile, household income estimates",
    opsecNotes: "Free daily lookup quota per IP address.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.6,
    ratingCount: 340,
    views: 21900,
    tags: ["people-search", "reverse-vin", "email-to-name", "address"]
  },
  {
    name: "Whitepages",
    categorySlug: "people-search",
    url: "https://www.whitepages.com",
    description: "The authoritative digital directory for contact information, background checks, landline phone numbers, and tenant screening.",
    usageContext: "Checking whether a phone number is registered as a mobile cellular device, landline, or virtual VoIP number (e.g. Google Voice).",
    inputOutput: "Input: Phone number or name | Output: Line type (Cell/Landline/VoIP), carrier name, owner name",
    opsecNotes: "VoIP numbers are commonly used by burner accounts and scammers.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.5,
    ratingCount: 310,
    views: 19500,
    tags: ["people-search", "whitepages", "voip-detection", "carrier-check"]
  },
  {
    name: "Radaris",
    categorySlug: "people-search",
    url: "https://radaris.com",
    description: "Public records search aggregating background information, social media mentions, property deeds, and professional licenses.",
    usageContext: "Discovering professional certifications, business affiliations, and state licenses held by an individual.",
    inputOutput: "Input: Full name | Output: Background report preview, associated businesses, professional history",
    opsecNotes: "Freemium service; public summary provides immediate basic facts.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.3,
    ratingCount: 180,
    views: 11200,
    tags: ["people-search", "licenses", "property-records", "freemium"]
  },

  // --- 15. NETWORK INFRASTRUCTURE & BGP ---
  {
    name: "PeeringDB",
    categorySlug: "network-routing",
    url: "https://www.peeringdb.com",
    description: "Freely available, user-maintained database of networks, internet exchange points (IXPs), data centers, and interconnection facilities.",
    usageContext: "Determining where an internet service provider physically connects with other networks and in which co-location facilities.",
    inputOutput: "Input: ASN or Organization name | Output: Connected IXPs, public peering exchange points, physical colocation facilities",
    opsecNotes: "Critical for understanding global internet backbone connectivity and transit relationships.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 340,
    views: 21500,
    tags: ["network-routing", "peeringdb", "ixp", "data-centers", "interconnection"]
  },
  {
    name: "RIPEstat",
    categorySlug: "network-routing",
    url: "https://stat.ripe.net",
    description: "RIPE NCC's open data platform providing comprehensive visual intelligence on IP address space, ASNs, routing history, and abuse contacts.",
    usageContext: "Investigating European/Middle Eastern IP allocations, BGP routing anomalies, and historical whois changes.",
    inputOutput: "Input: IP address, prefix, or AS Number | Output: Visual routing history, RPKI validation status, reverse DNS delegations",
    opsecNotes: "Official Regional Internet Registry (RIR) platform; authoritative source.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 370,
    views: 23800,
    tags: ["network-routing", "ripestat", "rir", "rpki", "routing-history"]
  },
  {
    name: "SSL Labs Server Test",
    categorySlug: "network-routing",
    url: "https://www.ssllabs.com/ssltest/",
    description: "Qualys SSL Labs deep analysis of the SSL/TLS configuration of any public web server, testing cipher suites, certificates, and vulnerabilities.",
    usageContext: "Evaluating server security hygiene, uncovering misconfigured certificates, and testing for Heartbleed, POODLE, and DROWN.",
    inputOutput: "Input: Hostname | Output: Letter grade (A+ to F), certificate chain, supported TLS versions, cipher suite priority",
    opsecNotes: "Tick 'Do not show results on the boards' if you do not want your target displayed on Qualys public scan list.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 580,
    views: 37000,
    tags: ["network-routing", "ssl-labs", "tls-audit", "cipher-suites", "qualys"]
  },
  {
    name: "CAIDA AS Rank",
    categorySlug: "network-routing",
    url: "https://asrank.caida.org",
    description: "Ranks Autonomous Systems (ASNs) based on their customer cone size, showing the most influential tier-1 transit backbones in the world.",
    usageContext: "Identifying which tier-1 transit providers route internet traffic for a specific country or bulletproof host.",
    inputOutput: "Input: ASN or Org | Output: Global rank, customer cone ASN count, prefixes announced",
    opsecNotes: "Academic rigor provided by the Center for Applied Internet Data Analysis (UC San Diego).",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 190,
    views: 12100,
    tags: ["network-routing", "caida", "as-rank", "tier1-transit", "academic"]
  },
  {
    name: "DNSlytics",
    categorySlug: "network-routing",
    url: "https://dnslytics.com",
    description: "Domain and IP network analytics platform linking together shared IP addresses, Google AdSense IDs, nameservers, and MX servers.",
    usageContext: "Mapping out full digital estates and affiliate networks owned by the same organization.",
    inputOutput: "Input: Domain, IP, or Google ID | Output: Connected websites, reverse analytics reports, network hosting summary",
    opsecNotes: "Powerful pivot engine for linking disparate domains.",
    toolFlags: "R",
    isFree: 2,
    ratingAvg: 4.6,
    ratingCount: 220,
    views: 14400,
    tags: ["network-routing", "dnslytics", "adsense-pivot", "network-estate"]
  },

  // --- 16. WIRELESS, RF & MARITIME SIGNALS ---
  {
    name: "WiGLE.net (Wireless Network Mapping)",
    categorySlug: "wireless-rf",
    url: "https://wigle.net",
    description: "The world's largest database of wireless networks and cell towers, mapping over 1 billion Wi-Fi networks with BSSID coordinates.",
    usageContext: "Geolocating a target using a captured Wi-Fi MAC address (BSSID) from a photo, router log, or network probe.",
    inputOutput: "Input: BSSID (MAC address) or SSID | Output: Exact geographic map coordinates, signal encryption, first/last seen dates",
    opsecNotes: "Wi-Fi BSSID geolocation can locate an exact apartment room or household.",
    toolFlags: "R",
    isFree: 1,
    ratingAvg: 5.0,
    ratingCount: 680,
    views: 43500,
    tags: ["wireless-rf", "wigle", "bssid", "wifi-geolocation", "essential"]
  },
  {
    name: "RadioReference.com",
    categorySlug: "wireless-rf",
    url: "https://www.radioreference.com",
    description: "The world's largest radio communications data provider, featuring complete frequency databases for police, fire, EMS, aviation, and rail.",
    usageContext: "Listening to live public safety emergency dispatches and identifying radio frequency trunked systems.",
    inputOutput: "Input: County, agency, or frequency | Output: Radio frequency tables, PL tones, live audio feeds",
    opsecNotes: "Monitors active first-responder radio traffic during breaking crises.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 390,
    views: 25000,
    tags: ["wireless-rf", "police-scanner", "frequencies", "radio-reference", "emergency"]
  },
  {
    name: "OpenCelliD",
    categorySlug: "wireless-rf",
    url: "https://opencellid.org",
    description: "The world's largest open database of 40+ million cell towers and cellular base stations across GSM, UMTS, LTE, and 5G.",
    usageContext: "Triangulating phone positions and mapping cellular tower infrastructure for Cell IDs (CID, LAC, MCC, MNC).",
    inputOutput: "Input: MCC, MNC, LAC, CellID | Output: Geographic position of cell tower on interactive map",
    opsecNotes: "Open-source dataset free for community access.",
    toolFlags: "R",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 280,
    views: 18100,
    tags: ["wireless-rf", "cell-towers", "opencellid", "lte", "triangulation"]
  },
  {
    name: "WebSDR.org",
    categorySlug: "wireless-rf",
    url: "http://websdr.org",
    description: "Directory of Software-Defined Radio receivers connected to the internet, allowing anyone to listen to shortwave and amateur radio live.",
    usageContext: "Listening to military shortwave transmissions, numbers stations, maritime distress frequencies, and amateur ham broadcasts worldwide.",
    inputOutput: "Input: Frequency (kHz/MHz) + Modulation | Output: Live audio stream with waterfall spectrum display",
    opsecNotes: "Monitor high-frequency (HF) radio signals from multiple geographic vantage points simultaneously.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.9,
    ratingCount: 420,
    views: 27500,
    tags: ["wireless-rf", "websdr", "shortwave", "sdr", "radio-signals"]
  },
  {
    name: "APRS.fi",
    categorySlug: "wireless-rf",
    url: "https://aprs.fi",
    description: "Automatic Packet Reporting System (APRS) tracking map showing live amateur radio stations, weather beacons, and mobile ham GPS trackers.",
    usageContext: "Tracking amateur radio operators, emergency disaster communications teams, and high-altitude weather balloons.",
    inputOutput: "Input: Ham radio callsign or map location | Output: Real-time GPS track, altitude, telemetry data, packet logs",
    opsecNotes: "All APRS transmissions are unencrypted public radio broadcasts.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.7,
    ratingCount: 230,
    views: 14800,
    tags: ["wireless-rf", "aprs", "ham-radio", "telemetry", "tracking"]
  },
  {
    name: "SkyVector Aeronautical Charts",
    categorySlug: "wireless-rf",
    url: "https://skyvector.com",
    description: "Worldwide aeronautical navigation charts (VFR sectional, IFR high/low enroute) with live weather, NOTAMs, and flight planning.",
    usageContext: "Analyzing airspace restrictions, military restricted zones, flight corridors, and airport navigational aids.",
    inputOutput: "Input: Airport code or airspace coordinates | Output: High-resolution sectional aviation charts and NOTAM notices",
    opsecNotes: "Cross-reference with flight tracking tools to understand why aircraft avoid certain airspace sectors.",
    toolFlags: "T",
    isFree: 1,
    ratingAvg: 4.8,
    ratingCount: 310,
    views: 19900,
    tags: ["wireless-rf", "aviation", "charts", "notam", "airspace"]
  }
];
